# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import asyncio
from pathlib import Path

from . import address as address
from . import alias as alias
from . import byte_cache as byte_cache
from . import copy_rename_fallback as copy_rename_fallback
from . import file as file
from . import metadata_cache as metadata_cache
from . import plugin as plugin
from . import redirect_follower as redirect_follower
from . import retry as retry
from . import router as router

# Compatibility projections for native-only/deferred stream protocols.
# AliasRequest, SecretBundle, AuthEvent, AsyncAuthEventStream,
# AsyncAddressRootSnapshotStream, and AsyncReadStream remain importable even
# though declaration-form Python layers do not author those protocol families.
from .ovstorage import (
    ANONYMOUS_PRINCIPAL_ID as ANONYMOUS_PRINCIPAL_ID,
    AccessDecision as AccessDecision,
    AddressRoot as AddressRoot,
    AddressVisibilityOverride as AddressVisibilityOverride,
    Alias as Alias,
    AliasChainTooLongError as AliasChainTooLongError,
    AliasRequest as AliasRequest,
    AlreadyExistsError as AlreadyExistsError,
    AsyncAddressRootSnapshotStream as AsyncAddressRootSnapshotStream,
    AsyncAuthEventStream as AsyncAuthEventStream,
    AsyncBodyInput as AsyncBodyInput,
    AsyncChangeEventStream as AsyncChangeEventStream,
    AsyncReadStream as AsyncReadStream,
    AuthCancelledError as AuthCancelledError,
    AuthCredential as AuthCredential,
    AuthEvent as AuthEvent,
    AuthExpiredError as AuthExpiredError,
    AuthRequiredError as AuthRequiredError,
    AuthorizationLeaseExpiredError as AuthorizationLeaseExpiredError,
    BackendKindDescriptor as BackendKindDescriptor,
    BrokerRequiredError as BrokerRequiredError,
    BrokerUnavailableError as BrokerUnavailableError,
    CacheCorruptError as CacheCorruptError,
    CacheLockContentionError as CacheLockContentionError,
    CancelledBucketError as CancelledBucketError,
    CancelledError as CancelledError,
    Capabilities as Capabilities,
    ChangeEvent as ChangeEvent,
    CommitAmbiguousError as CommitAmbiguousError,
    PartialCompletionError as PartialCompletionError,
    ConfigValue as ConfigValue,
    ConflictError as ConflictError,
    Connection as Connection,
    ConnectionRequest as ConnectionRequest,
    ContentChecksumMismatchError as ContentChecksumMismatchError,
    ContentMismatchError as ContentMismatchError,
    CredentialCacheDurability as CredentialCacheDurability,
    CredentialExpiredError as CredentialExpiredError,
    CredentialUnavailableError as CredentialUnavailableError,
    DeadlineExceededError as DeadlineExceededError,
    DirectoryNotEmptyError as DirectoryNotEmptyError,
    EXT_AUTH_CREDENTIAL as EXT_AUTH_CREDENTIAL,
    EXT_PRINCIPAL_DISPLAY_NAME as EXT_PRINCIPAL_DISPLAY_NAME,
    EXT_PRINCIPAL_ID as EXT_PRINCIPAL_ID,
    Error as Error,
    IncompatibleTypeError as IncompatibleTypeError,
    Info as Info,
    IntegrityFailureError as IntegrityFailureError,
    InteractiveAuthCapability as InteractiveAuthCapability,
    InternalBucketError as InternalBucketError,
    InternalError as InternalError,
    InvalidArgumentError as InvalidArgumentError,
    InvalidBucketError as InvalidBucketError,
    LayerBase as LayerBase,
    ListPage as ListPage,
    LocalDelegate as LocalDelegate,
    LockedError as LockedError,
    NamedPipeTransport as NamedPipeTransport,
    NetworkFilesystemRefusedError as NetworkFilesystemRefusedError,
    NoRouteError as NoRouteError,
    NotConfiguredError as NotConfiguredError,
    NotFoundBucketError as NotFoundBucketError,
    NotFoundError as NotFoundError,
    ObjectModifiedError as ObjectModifiedError,
    PermissionBucketError as PermissionBucketError,
    PermissionDeniedError as PermissionDeniedError,
    PluginRegistry as PluginRegistry,
    PluginRejectedError as PluginRejectedError,
    PolicyEpochStaleError as PolicyEpochStaleError,
    PreconditionBucketError as PreconditionBucketError,
    PreconditionFailedError as PreconditionFailedError,
    RedirectExpiredError as RedirectExpiredError,
    ResourceExhaustedBucketError as ResourceExhaustedBucketError,
    ResourceExhaustedError as ResourceExhaustedError,
    RouteConflictError as RouteConflictError,
    SecretBundle as SecretBundle,
    SecretValue as SecretValue,
    Stack as Stack,
    StagingExpiredError as StagingExpiredError,
    StateRootUnavailableError as StateRootUnavailableError,
    TcpTransport as TcpTransport,
    TransientBucketError as TransientBucketError,
    TransientError as TransientError,
    UdsTransport as UdsTransport,
    UnsupportedBucketError as UnsupportedBucketError,
    UnsupportedError as UnsupportedError,
    VersionPage as VersionPage,
    __version__ as __version__,
    init_auth_substrate as init_auth_substrate,
)

def bundled_plugins_dir() -> Path: ...

class OwnedLoop:
    def __init__(self) -> None: ...
    @property
    def loop(self) -> asyncio.AbstractEventLoop: ...
    def close(self) -> None: ...
    def __enter__(self) -> OwnedLoop: ...
    def __exit__(self, *_exc: object) -> None: ...

__all__ = [
    "ANONYMOUS_PRINCIPAL_ID",
    "AccessDecision",
    "AddressRoot",
    "AddressVisibilityOverride",
    "Alias",
    "AliasChainTooLongError",
    "AliasRequest",
    "AlreadyExistsError",
    "AsyncAddressRootSnapshotStream",
    "AsyncAuthEventStream",
    "AsyncBodyInput",
    "AsyncChangeEventStream",
    "AsyncReadStream",
    "AuthCancelledError",
    "AuthCredential",
    "AuthEvent",
    "AuthExpiredError",
    "AuthRequiredError",
    "AuthorizationLeaseExpiredError",
    "BackendKindDescriptor",
    "BrokerRequiredError",
    "BrokerUnavailableError",
    "CacheCorruptError",
    "CacheLockContentionError",
    "CancelledBucketError",
    "CancelledError",
    "Capabilities",
    "ChangeEvent",
    "CommitAmbiguousError",
    "PartialCompletionError",
    "ConfigValue",
    "ConflictError",
    "Connection",
    "ConnectionRequest",
    "ContentChecksumMismatchError",
    "ContentMismatchError",
    "CredentialCacheDurability",
    "CredentialExpiredError",
    "CredentialUnavailableError",
    "DeadlineExceededError",
    "DirectoryNotEmptyError",
    "EXT_AUTH_CREDENTIAL",
    "EXT_PRINCIPAL_DISPLAY_NAME",
    "EXT_PRINCIPAL_ID",
    "Error",
    "IncompatibleTypeError",
    "Info",
    "IntegrityFailureError",
    "InteractiveAuthCapability",
    "InternalBucketError",
    "InternalError",
    "InvalidArgumentError",
    "InvalidBucketError",
    "LayerBase",
    "ListPage",
    "LocalDelegate",
    "LockedError",
    "NamedPipeTransport",
    "NetworkFilesystemRefusedError",
    "NoRouteError",
    "NotConfiguredError",
    "NotFoundBucketError",
    "NotFoundError",
    "ObjectModifiedError",
    "PermissionBucketError",
    "PermissionDeniedError",
    "PluginRegistry",
    "PluginRejectedError",
    "PolicyEpochStaleError",
    "PreconditionBucketError",
    "PreconditionFailedError",
    "RedirectExpiredError",
    "ResourceExhaustedBucketError",
    "ResourceExhaustedError",
    "RouteConflictError",
    "SecretBundle",
    "SecretValue",
    "Stack",
    "StagingExpiredError",
    "StateRootUnavailableError",
    "TcpTransport",
    "TransientBucketError",
    "TransientError",
    "UdsTransport",
    "UnsupportedBucketError",
    "UnsupportedError",
    "VersionPage",
    "__version__",
    "address",
    "alias",
    "byte_cache",
    "copy_rename_fallback",
    "file",
    "init_auth_substrate",
    "metadata_cache",
    "plugin",
    "redirect_follower",
    "retry",
    "router",
]
