# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

__all__ = [
    "is_directory",
    "is_prefix_of",
    "join_relative",
    "key",
    "parent_and_name",
    "parse",
    "replace_prefix",
    "strip_prefix",
    "to_directory",
    "with_query_pair",
]


def is_directory(address: str) -> bool: ...
def is_prefix_of(prefix: str, address: str) -> bool: ...
def join_relative(address: str, relative_path: str) -> str: ...
def key(address: str) -> str: ...
def parent_and_name(address: str) -> tuple[str, str] | None: ...
def parse(address: str) -> str: ...
def replace_prefix(address: str, prefix: str, replacement: str) -> str: ...
def strip_prefix(address: str, prefix: str) -> str | None: ...
def to_directory(address: str) -> str: ...
def with_query_pair(address: str, key: str, value: str) -> str: ...
