// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

syntax = "proto3";

package nvidia.omniverse.storage.fileobject.v1beta;

import "google/protobuf/timestamp.proto";

option go_package = "pb.api.nvidia.com/omniverse/storage/fileobject/v1beta;storage";
option java_multiple_files = true;
option java_outer_classname = "FileobjectProto";
option java_package = "com.nvidia.omniverse.storage.fileobject.v1beta";

// The Chunk message is used to transport a part of the data object stored.
// Type is bytes, with an application specific encoding that is not interpreted by the storage service
message Chunk {
  // The (partial) data object itself
  bytes chunk = 1;
}

// The Metadata message contains all metadata of a data object.
// The fields have presence bits to help the client protect against invalid messages using wrong defaults.
// Zero trust policy requires the client checking the presence of fields.
//
// Some fields are optional to be sent by a properly implemented Storage Service.
message Metadata {
  // Total size of data object in bytes
  optional uint64 data_object_size = 1;
  // Timestamp (UTC) of the last modification of the object. Exact semantics and precision are storage-type specific. This field may be omitted.
  optional google.protobuf.Timestamp last_modified_timestamp = 2;
}

// HTTP header
message Header {
  // name of header case-insensitive
  string name = 1;
  // value of header
  string value = 2;
}

// On receiving a redirect message, the storage service client has to retrieve the data object from the URL given
message Redirect {
  // URL that can be used to retrieve the data object
  string redirect_target_url = 1;
  // Method type to access, case-insensitive
  string method = 2 [deprecated = true];
  // Pack of headers that client should use to access cloud storage
  repeated Header additional_headers = 3;
}

// The AddressInfo messages are produced by the Enumerate() function and contain information about sub-resource-addresses found
message AddressInfo {
  // Resource address of the child object
  string resource_address = 1;
  // Some metadata of the object stored currently at that address
  Metadata metadata = 2;
}

// The ResourceInfo message contains the information about a single data object as retrieved by Stat() or Enumerate()
message ResourceInfo {
  // The ResourceIdentity of the data object, which can be used to download the data via Read()
  ResourceIdentity resource_identity = 1;
  // The Metadata of the data object
  Metadata metadata = 2;
}

// The ResourceIdentity message is used to transport all information required by the storage service to perform a Read() operation of that object at a later point in time
message ResourceIdentity {
  // Storage service specific data that is delivered by ResourceInfo messages, and used by Read() operations
  string encoded_identity = 1;
}
