# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ovstorage-plugin"
version = "0.1.0"
edition = "2024"
description = "Plugin ABI traits, manifest types, and loader for ovstorage."
license = "Apache-2.0"
build = "build.rs"

[dependencies]
async-channel.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
libloading.workspace = true
ovstorage-plugin-macros = { version = "0.1.0", path = "../ovstorage-plugin-macros" }
parking_lot.workspace = true
regex.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
zeroize.workspace = true

[build-dependencies]
cbindgen.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
