# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ovstorage-example-plugin-rust"
version = "0.1.0"
edition = "2024"
description = "Example Rust plugin for ovstorage."
license = "Apache-2.0"
publish = false

[dependencies]
ovstorage-plugin = { version = "0.1.0", path = "../../crates/ovstorage-plugin" }
async-trait.workspace = true

[lib]
name = "ovstorage_plugin_example_rust"
crate-type = ["cdylib"]
path = "src/lib.rs"

[lints]
workspace = true
