/* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * ovstorage plugin C ABI.
 *
 * Generated by cbindgen from crates/ovstorage-plugin/src/ffi.rs.
 * Do not edit by hand: edit the Rust source and rerun `cargo build` on the
 * crate. The build script regenerates this file in-place; the file is
 * checked in for code review and IDE consumption.
 */


#ifndef OVSTORAGE_PLUGIN_H
#define OVSTORAGE_PLUGIN_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C ABI version this header was generated against. Mismatch between
 * the host's value and the plugin's manifest surfaces as
 * `IncompatibleType` before any vtable call is attempted.
 *
 * History:
 * - v1: initial SPI.
 * - v2: `Capabilities` gains `supports_write`, `supports_write_stream`,
 *   `supports_write_redirect`, `supports_delete`,
 *   `supports_create_directory`, `supports_delete_directory` to gate
 *   the four methods that moved from required to default `Unsupported`
 *   on the `Backend` trait. Layout change; cdylibs must rebuild.
 * - v3: precondition SPI redesign. `ObjectIdentity` removed; `etag` /
 *   `version` / `size` / `mtime_unix_ms` lift onto `ObjectInfo` and
 *   `BackendItemInfo`. New `ObjectKindV1` discriminator replaces
 *   `SubdirKindV1`. New `IfDestExistsV1` tagged-union on
 *   `WriteOptions` / `CopyOptions` / `RenameOptions` replaces the
 *   `no_overwrite` boolean and the old `if_match: ObjectIdentity`.
 *   `CopyOptions` / `RenameOptions` add `if_source` (etag). Read /
 *   delete / update-metadata `if_match` becomes `Optional<Str>`.
 *   Change events carry `etag: Optional<Str>` in place of
 *   `identity: Optional<ObjectIdentity>`. Error context's identity
 *   payload carries `new_etag: Optional<Str>`.
 * - v4: list, list_versions, and get_latest_version return
 *   `ObjectInfo` directly. Backend list/version wrapper payloads and
 *   version selector structs are removed.
 */
#define OVSTORAGE_PLUGIN_ABI_VERSION 4

/**
 * Tag for [`BackendChangeEvent`].
 */
typedef enum {
  OvStoragePlugin_BackendChangeEventTag_Object = 0,
  OvStoragePlugin_BackendChangeEventTag_Lapsed = 1,
} OvStoragePlugin_BackendChangeEventTag;

/**
 * `ChangeKind` discriminant.
 */
typedef enum {
  OvStoragePlugin_ChangeKind_Created = 0,
  OvStoragePlugin_ChangeKind_Modified = 1,
  OvStoragePlugin_ChangeKind_Deleted = 2,
  OvStoragePlugin_ChangeKind_MetadataChanged = 3,
} OvStoragePlugin_ChangeKind;

/**
 * Three-state status returned by a stream's `next_fn`.
 */
typedef enum {
  /**
   * `out_item` has been written; continue calling `next_fn`.
   */
  OvStoragePlugin_StreamStep_Yielded = 0,
  /**
   * Stream is exhausted; neither out-pointer is written. Subsequent
   * calls are no-ops.
   */
  OvStoragePlugin_StreamStep_Ended = 1,
  /**
   * `out_error` written; the stream is now exhausted. Subsequent
   * calls are no-ops.
   */
  OvStoragePlugin_StreamStep_Failed = 2,
} OvStoragePlugin_StreamStep;

/**
 * Tag for [`AuthEvent`].
 */
typedef enum {
  OvStoragePlugin_AuthEventTag_OpenBrowser = 0,
  OvStoragePlugin_AuthEventTag_DeviceCode = 1,
  OvStoragePlugin_AuthEventTag_Progress = 2,
  OvStoragePlugin_AuthEventTag_Succeeded = 3,
  OvStoragePlugin_AuthEventTag_Failed = 4,
  OvStoragePlugin_AuthEventTag_Cancelled = 5,
} OvStoragePlugin_AuthEventTag;

/**
 * Tag for [`ConnectionSource`].
 */
typedef enum {
  OvStoragePlugin_ConnectionSourceTag_Static = 0,
  OvStoragePlugin_ConnectionSourceTag_Runtime = 1,
  OvStoragePlugin_ConnectionSourceTag_BrokerDelivered = 2,
} OvStoragePlugin_ConnectionSourceTag;

/**
 * Configuration source layer.
 */
typedef enum {
  OvStoragePlugin_ConfigLayer_Programmatic = 0,
  OvStoragePlugin_ConfigLayer_Env = 1,
  OvStoragePlugin_ConfigLayer_Project = 2,
  OvStoragePlugin_ConfigLayer_User = 3,
  OvStoragePlugin_ConfigLayer_Machine = 4,
} OvStoragePlugin_ConfigLayer;

/**
 * `VersionListOrder` discriminant.
 */
typedef enum {
  OvStoragePlugin_VersionListOrder_Newest = 0,
  OvStoragePlugin_VersionListOrder_Oldest = 1,
  OvStoragePlugin_VersionListOrder_Unordered = 2,
} OvStoragePlugin_VersionListOrder;

/**
 * Tag for [`ConnectionAuthState`].
 */
typedef enum {
  OvStoragePlugin_ConnectionAuthStateTag_Authenticated = 0,
  OvStoragePlugin_ConnectionAuthStateTag_AwaitingAuth = 1,
  OvStoragePlugin_ConnectionAuthStateTag_AuthFailed = 2,
  OvStoragePlugin_ConnectionAuthStateTag_Anonymous = 3,
} OvStoragePlugin_ConnectionAuthStateTag;

/**
 * Tag for [`AuthReason`].
 */
typedef enum {
  OvStoragePlugin_AuthReasonTag_NeverAuthenticated = 0,
  OvStoragePlugin_AuthReasonTag_RefreshTokenExpired = 1,
  OvStoragePlugin_AuthReasonTag_RefreshTokenRevoked = 2,
  OvStoragePlugin_AuthReasonTag_CredentialsRotated = 3,
  OvStoragePlugin_AuthReasonTag_ManuallyRequested = 4,
  OvStoragePlugin_AuthReasonTag_BackendUnreachable = 5,
  OvStoragePlugin_AuthReasonTag_Unknown = 6,
} OvStoragePlugin_AuthReasonTag;

/**
 * Stable error classification carried by every fallible call.
 * Discriminant values are the ABI contract.
 */
typedef enum {
  OvStoragePlugin_ErrorCode_NotFound = 0,
  OvStoragePlugin_ErrorCode_AlreadyExists = 1,
  OvStoragePlugin_ErrorCode_PermissionDenied = 2,
  OvStoragePlugin_ErrorCode_PreconditionFailed = 3,
  OvStoragePlugin_ErrorCode_Conflict = 4,
  OvStoragePlugin_ErrorCode_DirectoryNotEmpty = 5,
  OvStoragePlugin_ErrorCode_Unsupported = 6,
  OvStoragePlugin_ErrorCode_InvalidArgument = 7,
  OvStoragePlugin_ErrorCode_IncompatibleType = 8,
  OvStoragePlugin_ErrorCode_Locked = 9,
  OvStoragePlugin_ErrorCode_Cancelled = 10,
  OvStoragePlugin_ErrorCode_DeadlineExceeded = 11,
  OvStoragePlugin_ErrorCode_Transient = 12,
  OvStoragePlugin_ErrorCode_ResourceExhausted = 13,
  OvStoragePlugin_ErrorCode_IntegrityFailure = 14,
  OvStoragePlugin_ErrorCode_Internal = 15,
  OvStoragePlugin_ErrorCode_BrokerUnavailable = 16,
  OvStoragePlugin_ErrorCode_BrokerRequired = 17,
  OvStoragePlugin_ErrorCode_RedirectExpired = 18,
  OvStoragePlugin_ErrorCode_PolicyEpochStale = 19,
  OvStoragePlugin_ErrorCode_AuthorizationLeaseExpired = 20,
  OvStoragePlugin_ErrorCode_CacheCorrupt = 21,
  OvStoragePlugin_ErrorCode_StagingExpired = 22,
  OvStoragePlugin_ErrorCode_CommitAmbiguous = 23,
  OvStoragePlugin_ErrorCode_CacheLockContention = 24,
  OvStoragePlugin_ErrorCode_StateRootUnavailable = 25,
  OvStoragePlugin_ErrorCode_NetworkFilesystemRefused = 26,
  OvStoragePlugin_ErrorCode_ObjectModified = 27,
  OvStoragePlugin_ErrorCode_NoRoute = 28,
  OvStoragePlugin_ErrorCode_RouteConflict = 29,
  OvStoragePlugin_ErrorCode_NotConfigured = 30,
  OvStoragePlugin_ErrorCode_AliasChainTooLong = 31,
  OvStoragePlugin_ErrorCode_CredentialExpired = 32,
  OvStoragePlugin_ErrorCode_CredentialUnavailable = 33,
  OvStoragePlugin_ErrorCode_AuthRequired = 34,
  OvStoragePlugin_ErrorCode_AuthCancelled = 35,
  OvStoragePlugin_ErrorCode_AuthExpired = 36,
  OvStoragePlugin_ErrorCode_ContentMismatch = 37,
  OvStoragePlugin_ErrorCode_ContentChecksumMismatch = 38,
  OvStoragePlugin_ErrorCode_PluginRejected = 39,
} OvStoragePlugin_ErrorCode;

/**
 * Tag for [`SecretValue`].
 */
typedef enum {
  OvStoragePlugin_SecretValueTag_Bytes = 0,
  OvStoragePlugin_SecretValueTag_OAuthToken = 1,
  OvStoragePlugin_SecretValueTag_File = 2,
  OvStoragePlugin_SecretValueTag_MtlsCertPair = 3,
  OvStoragePlugin_SecretValueTag_SystemIdentity = 4,
} OvStoragePlugin_SecretValueTag;

/**
 * Discriminant for [`ErrorContextV1`]. New variants append; an
 * unrecognized discriminant means "context absent" per the SPI's
 * "ignore unknown" forward-compat rule.
 */
typedef enum {
  /**
   * Identity slot active. Companion to `ErrorCode::ObjectModified`.
   */
  OvStoragePlugin_ErrorContextKindV1_Identity = 0,
  /**
   * Auth slot active. Companion to `ErrorCode::AuthRequired` /
   * `AuthCancelled` / `AuthExpired`.
   */
  OvStoragePlugin_ErrorContextKindV1_Auth = 1,
} OvStoragePlugin_ErrorContextKindV1;

/**
 * Tag for [`BackendAddressRootsChange`]. Mirrors the variants of the
 * crate-root `AddressRootsChange` enum.
 */
typedef enum {
  OvStoragePlugin_BackendAddressRootsChangeTag_Snapshot = 0,
  OvStoragePlugin_BackendAddressRootsChangeTag_Added = 1,
  OvStoragePlugin_BackendAddressRootsChangeTag_Removed = 2,
} OvStoragePlugin_BackendAddressRootsChangeTag;

/**
 * File / directory discriminator. Numeric values are the ABI contract.
 *
 * - `File`: a regular object.
 * - `Directory`: native directory inode (POSIX file plugins, Nucleus,
 *   Azure ADLS Gen2 HNS).
 * - `DirectoryMarker`: zero-byte marker object on a flat-namespace
 *   backend (S3/GCS `dir/`-keyed objects).
 * - `DirectoryInferred`: directory inferred from descendant common
 *   prefixes by the dispatcher's marker-folding pass; no backing
 *   storage object.
 */
enum OvStoragePlugin_ObjectKindV1 {
  OvStoragePlugin_ObjectKindV1_File = 0,
  OvStoragePlugin_ObjectKindV1_Directory = 1,
  OvStoragePlugin_ObjectKindV1_DirectoryMarker = 2,
  OvStoragePlugin_ObjectKindV1_DirectoryInferred = 3,
};
typedef uint8_t OvStoragePlugin_ObjectKindV1;

/**
 * Tag for [`ReadResult`].
 */
typedef enum {
  OvStoragePlugin_ReadResultTag_Bytes = 0,
  OvStoragePlugin_ReadResultTag_LocalDelegate = 1,
  OvStoragePlugin_ReadResultTag_Redirect = 2,
  OvStoragePlugin_ReadResultTag_Stream = 3,
} OvStoragePlugin_ReadResultTag;

/**
 * Format hint for an `mtime` header parsed out of an HTTP response.
 */
typedef enum {
  OvStoragePlugin_MtimeFormat_Rfc1123 = 0,
  OvStoragePlugin_MtimeFormat_Iso8601 = 1,
  OvStoragePlugin_MtimeFormat_UnixSeconds = 2,
} OvStoragePlugin_MtimeFormat;

/**
 * Tag for [`IfDestExistsV1`].
 */
typedef enum {
  OvStoragePlugin_IfDestExistsTag_Overwrite = 0,
  OvStoragePlugin_IfDestExistsTag_Fail = 1,
  OvStoragePlugin_IfDestExistsTag_MatchEtag = 2,
} OvStoragePlugin_IfDestExistsTag;

/**
 * Tag for [`RedirectBodySource`].
 */
typedef enum {
  OvStoragePlugin_RedirectBodySourceTag_Empty = 0,
  OvStoragePlugin_RedirectBodySourceTag_UserBytes = 1,
  OvStoragePlugin_RedirectBodySourceTag_Inline = 2,
} OvStoragePlugin_RedirectBodySourceTag;

/**
 * Tag for [`WriteStep`].
 */
typedef enum {
  OvStoragePlugin_WriteStepTag_Done = 0,
  OvStoragePlugin_WriteStepTag_Redirects = 1,
} OvStoragePlugin_WriteStepTag;

/**
 * Tag for [`Body`].
 */
typedef enum {
  OvStoragePlugin_BodyTag_Bytes = 0,
  OvStoragePlugin_BodyTag_LocalFile = 1,
  OvStoragePlugin_BodyTag_Stream = 2,
} OvStoragePlugin_BodyTag;

/**
 * Tag for [`ConfigFieldKind`].
 */
typedef enum {
  OvStoragePlugin_ConfigFieldKindTag_Url = 0,
  OvStoragePlugin_ConfigFieldKindTag_Text = 1,
  OvStoragePlugin_ConfigFieldKindTag_Integer = 2,
  OvStoragePlugin_ConfigFieldKindTag_Bool = 3,
  OvStoragePlugin_ConfigFieldKindTag_Enum = 4,
  OvStoragePlugin_ConfigFieldKindTag_Path = 5,
} OvStoragePlugin_ConfigFieldKindTag;

/**
 * Tag for [`EnumSource`].
 */
typedef enum {
  OvStoragePlugin_EnumSourceTag_Static = 0,
  OvStoragePlugin_EnumSourceTag_Discovered = 1,
} OvStoragePlugin_EnumSourceTag;

/**
 * Tag for [`ConfigValue`].
 */
typedef enum {
  OvStoragePlugin_ConfigValueTag_String = 0,
  OvStoragePlugin_ConfigValueTag_Int = 1,
  OvStoragePlugin_ConfigValueTag_Bool = 2,
  /**
   * Reserialized TOML payload (nested table or array of tables).
   * Distinct from `String` so callers can round-trip nested
   * values without ambiguity.
   */
  OvStoragePlugin_ConfigValueTag_Toml = 3,
} OvStoragePlugin_ConfigValueTag;

/**
 * Host-declared interactive-auth capability. Discriminants are the
 * ABI contract; adding a variant is a breaking change.
 */
enum OvStoragePlugin_InteractiveAuthCapabilityV1 {
  OvStoragePlugin_InteractiveAuthCapabilityV1_None = 0,
  OvStoragePlugin_InteractiveAuthCapabilityV1_Headless = 1,
  OvStoragePlugin_InteractiveAuthCapabilityV1_Browser = 2,
};
typedef uint8_t OvStoragePlugin_InteractiveAuthCapabilityV1;

/**
 * Shared state behind a [`CancelTokenFFI`]. Opaque to foreign code;
 * access exclusively via the vtable's function pointers.
 */
typedef struct OvStoragePlugin_AtomicCancelState OvStoragePlugin_AtomicCancelState;

/**
 * Owned UTF-8 string buffer. `ptr` is never null; `len` bounds the
 * reads (the buffer is NOT NUL-terminated). UTF-8 validity is
 * enforced at marshalling time. Empty strings carry `len == 0` and
 * a one-byte sentinel allocation.
 */
typedef struct {
  char *ptr;
  size_t len;
} OvStoragePlugin_Str;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_Str value;
} OvStoragePlugin_Optional_Str;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  uint64_t value;
} OvStoragePlugin_Optional_u64;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  int64_t value;
} OvStoragePlugin_Optional_i64;

/**
 * Owned byte buffer. Same allocator convention as [`Str`]; no UTF-8
 * requirement.
 */
typedef struct {
  uint8_t *ptr;
  size_t len;
} OvStoragePlugin_Bytes;

/**
 * Opaque watch-directory cursor. Bytes are plugin-defined; hosts
 * pass them back via `WatchDirectoryOptions::since` and MUST NOT
 * inspect, hash, or split them.
 */
typedef struct {
  OvStoragePlugin_Bytes bytes;
} OvStoragePlugin_WatchDirectoryCursor;

/**
 * `BackendChangeEvent::Object` payload.
 *
 * `mtime_unix_ms` is Unix milliseconds; ms precision is the
 * FFI-boundary clock contract.
 */
typedef struct {
  OvStoragePlugin_Str address;
  OvStoragePlugin_ChangeKind kind;
  /**
   * Etag of the object after the change. Opaque precondition token.
   */
  OvStoragePlugin_Optional_Str etag;
  /**
   * Backend-specific version identifier when the notification
   * carries it.
   */
  OvStoragePlugin_Optional_Str version;
  /**
   * Object size in bytes when the notification carries it.
   */
  OvStoragePlugin_Optional_u64 size;
  /**
   * Last-modified time of the object after the change in Unix
   * milliseconds, when the notification carries it.
   */
  OvStoragePlugin_Optional_i64 mtime_unix_ms;
  int64_t at_unix_ms;
  OvStoragePlugin_WatchDirectoryCursor cursor;
} OvStoragePlugin_BackendChangeEventObject;

/**
 * `BackendChangeEvent::Lapsed` payload.
 */
typedef struct {
  OvStoragePlugin_Optional_i64 since_unix_ms;
  OvStoragePlugin_WatchDirectoryCursor cursor;
} OvStoragePlugin_BackendChangeEventLapsed;

/**
 * One change event yielded by a [`BackendChangeStream`].
 */
typedef struct {
  OvStoragePlugin_BackendChangeEventTag tag;
  OvStoragePlugin_BackendChangeEventObject object;
  OvStoragePlugin_BackendChangeEventLapsed lapsed;
} OvStoragePlugin_BackendChangeEvent;

/**
 * `AuthEvent::OpenBrowser` payload.
 */
typedef struct {
  OvStoragePlugin_Str url;
  int64_t expires_at_unix_ms;
} OvStoragePlugin_AuthEventOpenBrowser;

/**
 * `AuthEvent::DeviceCode` payload.
 */
typedef struct {
  OvStoragePlugin_Str user_code;
  OvStoragePlugin_Str verification_url;
  int64_t expires_at_unix_ms;
  uint64_t interval_ms;
} OvStoragePlugin_AuthEventDeviceCode;

/**
 * `AuthEvent::Progress` payload.
 */
typedef struct {
  OvStoragePlugin_Str message;
} OvStoragePlugin_AuthEventProgress;

/**
 * Opaque connection identifier (UUID encoded as a string).
 */
typedef struct {
  OvStoragePlugin_Str id;
} OvStoragePlugin_ConnectionId;

/**
 * `ConnectionSource::Static` payload.
 */
typedef struct {
  OvStoragePlugin_ConfigLayer layer;
} OvStoragePlugin_ConnectionSourceStatic;

/**
 * `ConnectionSource::Runtime` payload.
 */
typedef struct {
  bool persisted;
} OvStoragePlugin_ConnectionSourceRuntime;

/**
 * `ConnectionSource::BrokerDelivered` payload.
 */
typedef struct {
  OvStoragePlugin_Str broker_principal;
} OvStoragePlugin_ConnectionSourceBrokerDelivered;

/**
 * Where a connection came from.
 */
typedef struct {
  OvStoragePlugin_ConnectionSourceTag tag;
  OvStoragePlugin_ConnectionSourceStatic static_;
  OvStoragePlugin_ConnectionSourceRuntime runtime;
  OvStoragePlugin_ConnectionSourceBrokerDelivered broker_delivered;
} OvStoragePlugin_ConnectionSource;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_VersionListOrder value;
} OvStoragePlugin_Optional_VersionListOrder;

/**
 * `ChangeKindSet` bitset-style flag struct.
 */
typedef struct {
  bool created;
  bool modified;
  bool deleted;
  bool metadata_changed;
} OvStoragePlugin_ChangeKindSet;

/**
 * Capability bitset reported by the plugin per backend instance.
 */
typedef struct {
  bool supports_if_match_write;
  bool supports_no_overwrite_write;
  bool supports_native_metadata_patch;
  bool supports_metadata_rewrite_emulation;
  bool writes_are_atomic;
  bool supports_server_side_copy;
  bool supports_server_side_rename;
  bool supports_atomic_rename;
  bool has_real_directories;
  bool supports_write;
  bool supports_write_stream;
  bool supports_write_redirect;
  bool supports_delete;
  bool supports_list;
  bool wants_list_backed_stat;
  bool supports_recursive_list;
  bool populates_subdirectory_metadata;
  bool supports_create_directory;
  bool supports_delete_directory;
  bool supports_version_listing;
  OvStoragePlugin_Optional_VersionListOrder version_list_order;
  bool populates_effective_permissions_on_stat;
  bool supports_access_check;
  bool supports_watch_directory;
  OvStoragePlugin_ChangeKindSet watch_directory_kinds;
  bool watch_directory_resumable;
  OvStoragePlugin_Optional_u64 watch_directory_max_lag_ms;
  OvStoragePlugin_Optional_u64 redirect_size_threshold;
} OvStoragePlugin_Capabilities;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_Str *ptr;
  size_t len;
} OvStoragePlugin_List_Str;

/**
 * `ConnectionAuthState::Authenticated` payload.
 */
typedef struct {
  int64_t last_authenticated_at_unix_ms;
  OvStoragePlugin_Optional_i64 expires_at_unix_ms;
} OvStoragePlugin_ConnectionAuthStateAuthenticated;

/**
 * Why a connection is awaiting authentication. `Unknown` carries a
 * free-form details string.
 */
typedef struct {
  OvStoragePlugin_AuthReasonTag tag;
  OvStoragePlugin_Str unknown_details;
} OvStoragePlugin_AuthReason;

/**
 * Inline `(code, message)` pair for state-shaped fields where the
 * owning `Error` cannot be used (it is return-shaped).
 */
typedef struct {
  OvStoragePlugin_ErrorCode code;
  OvStoragePlugin_Str message;
} OvStoragePlugin_AuthAttemptError;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_AuthAttemptError value;
} OvStoragePlugin_Optional_AuthAttemptError;

/**
 * One auth-attempt record.
 */
typedef struct {
  int64_t at_unix_ms;
  OvStoragePlugin_Optional_AuthAttemptError error;
} OvStoragePlugin_AuthAttempt;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_AuthAttempt value;
} OvStoragePlugin_Optional_AuthAttempt;

/**
 * `ConnectionAuthState::AwaitingAuth` payload.
 */
typedef struct {
  OvStoragePlugin_AuthReason reason;
  OvStoragePlugin_Optional_AuthAttempt last_attempt;
} OvStoragePlugin_ConnectionAuthStateAwaitingAuth;

/**
 * `ConnectionAuthState::AuthFailed` payload (inline error).
 */
typedef struct {
  OvStoragePlugin_ErrorCode error_code;
  OvStoragePlugin_Str error_message;
  uint32_t attempts;
} OvStoragePlugin_ConnectionAuthStateAuthFailed;

/**
 * Persisted auth state of a connection.
 */
typedef struct {
  OvStoragePlugin_ConnectionAuthStateTag tag;
  OvStoragePlugin_ConnectionAuthStateAuthenticated authenticated;
  OvStoragePlugin_ConnectionAuthStateAwaitingAuth awaiting_auth;
  OvStoragePlugin_ConnectionAuthStateAuthFailed auth_failed;
} OvStoragePlugin_ConnectionAuthState;

/**
 * Single `(String, String)` entry inside a [`KeyValueList`].
 */
typedef struct {
  OvStoragePlugin_Str key;
  OvStoragePlugin_Str value;
} OvStoragePlugin_KeyValuePair;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_KeyValuePair *ptr;
  size_t len;
} OvStoragePlugin_List_KeyValuePair;

/**
 * Owned `(String, String)` list. Iteration order is not promised.
 */
typedef OvStoragePlugin_List_KeyValuePair OvStoragePlugin_KeyValueList;

/**
 * Connection — a configured backend instance plus its auth state.
 */
typedef struct {
  OvStoragePlugin_ConnectionId id;
  OvStoragePlugin_Str backend_kind;
  OvStoragePlugin_Str display_name;
  OvStoragePlugin_ConnectionSource source;
  OvStoragePlugin_Capabilities capabilities;
  OvStoragePlugin_List_Str current_addresses;
  OvStoragePlugin_ConnectionAuthState auth_state;
  OvStoragePlugin_Optional_i64 last_probed_unix_ms;
  OvStoragePlugin_KeyValueList user_metadata;
} OvStoragePlugin_Connection;

/**
 * Secret bytes carrier. The FFI struct does NOT zeroize on drop;
 * receivers that consume the value into a non-FFI form zeroize on
 * the way back. Bytes may still need to flow into a downstream call.
 */
typedef struct {
  OvStoragePlugin_Bytes bytes;
} OvStoragePlugin_SecretBytes;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_SecretBytes value;
} OvStoragePlugin_Optional_SecretBytes;

/**
 * `SecretValue::OAuthToken` payload.
 */
typedef struct {
  OvStoragePlugin_SecretBytes token;
  OvStoragePlugin_Optional_SecretBytes refresh;
  OvStoragePlugin_Optional_i64 expires_at_unix_ms;
} OvStoragePlugin_SecretValueOAuthToken;

/**
 * `SecretValue::MtlsCertPair` payload.
 */
typedef struct {
  OvStoragePlugin_SecretBytes cert_pem;
  OvStoragePlugin_SecretBytes key_pem;
} OvStoragePlugin_SecretValueMtlsCertPair;

/**
 * One credential value in a [`SecretBundle`].
 */
typedef struct {
  OvStoragePlugin_SecretValueTag tag;
  OvStoragePlugin_SecretBytes bytes;
  OvStoragePlugin_SecretValueOAuthToken oauth_token;
  OvStoragePlugin_SecretBytes file;
  OvStoragePlugin_SecretValueMtlsCertPair mtls_cert_pair;
} OvStoragePlugin_SecretValue;

/**
 * `(field_name, secret_value)` entry inside a [`SecretBundle`].
 */
typedef struct {
  OvStoragePlugin_Str field;
  OvStoragePlugin_SecretValue value;
} OvStoragePlugin_SecretBundleEntry;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_SecretBundleEntry *ptr;
  size_t len;
} OvStoragePlugin_List_SecretBundleEntry;

/**
 * Owned secret bundle.
 */
typedef struct {
  OvStoragePlugin_List_SecretBundleEntry entries;
} OvStoragePlugin_SecretBundle;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_SecretBundle value;
} OvStoragePlugin_Optional_SecretBundle;

/**
 * `AuthEvent::Succeeded` payload — connection plus optional credentials
 * the host should install via `update_credentials`.
 */
typedef struct {
  OvStoragePlugin_Connection connection;
  OvStoragePlugin_Optional_SecretBundle credentials;
} OvStoragePlugin_AuthEventSucceeded;

/**
 * `AuthEvent::Failed` payload (inline error).
 */
typedef struct {
  OvStoragePlugin_ErrorCode error_code;
  OvStoragePlugin_Str error_message;
} OvStoragePlugin_AuthEventFailed;

/**
 * One auth-flow event yielded by an [`AuthEventStream`].
 */
typedef struct {
  OvStoragePlugin_AuthEventTag tag;
  OvStoragePlugin_AuthEventOpenBrowser open_browser;
  OvStoragePlugin_AuthEventDeviceCode device_code;
  OvStoragePlugin_AuthEventProgress progress;
  OvStoragePlugin_AuthEventSucceeded succeeded;
  OvStoragePlugin_AuthEventFailed failed;
} OvStoragePlugin_AuthEvent;

/**
 * Identity-context payload for [`ErrorContextV1`]. `new_etag` is
 * the etag the backend reported, distinct from the caller's
 * `if_match` / `if_dest` precondition.
 */
typedef struct {
  OvStoragePlugin_Optional_Str new_etag;
} OvStoragePlugin_IdentityErrorContextV1;

/**
 * Auth-context payload for [`ErrorContextV1`]. `expired_at_unix_ms`
 * is set only on `ErrorCode::AuthExpired`; clock encoding is Unix
 * milliseconds (the FFI-boundary contract).
 */
typedef struct {
  OvStoragePlugin_ConnectionId connection_id;
  OvStoragePlugin_Optional_Str reason;
  OvStoragePlugin_Optional_i64 expired_at_unix_ms;
} OvStoragePlugin_AuthErrorContextV1;

/**
 * Typed payload attached to an [`Error`] for variants whose
 * structured fields have a stable shape.
 *
 * Tagged union: `kind` selects the active slot; the other slots
 * carry unspecified bytes and must not be read. Released either by
 * the owning [`Error`]'s destructor or via
 * `ovstorage_plugin_error_context_free`.
 */
typedef struct {
  OvStoragePlugin_ErrorContextKindV1 kind;
  OvStoragePlugin_IdentityErrorContextV1 identity;
  OvStoragePlugin_AuthErrorContextV1 auth;
} OvStoragePlugin_ErrorContextV1;

/**
 * Owned error value crossing the FFI boundary.
 *
 * `message_ptr` is never null and points at a UTF-8 buffer of
 * `message_len` bytes (NOT NUL-terminated). An empty message uses
 * `message_len == 0` with a one-byte sentinel allocation so
 * consumers need not special-case the null pointer. Pass the struct
 * to `ovstorage_plugin_error_free` exactly once when done.
 *
 * `context` is non-null when the error variant carries a stable
 * structured payload (e.g. `AuthRequired` → auth slot), else NULL.
 * The owning side's destructor frees the context alongside the
 * message buffer.
 */
typedef struct {
  OvStoragePlugin_ErrorCode code;
  char *message_ptr;
  size_t message_len;
  OvStoragePlugin_ErrorContextV1 *context;
} OvStoragePlugin_Error;

/**
 * `next_fn` signature for [`AuthEventStream`].
 */
typedef OvStoragePlugin_StreamStep (*OvStoragePlugin_AuthEventNextFn)(void *state,
                                                                      OvStoragePlugin_AuthEvent *out_item,
                                                                      OvStoragePlugin_Error *out_error);

/**
 * `drop_fn` signature shared by every stream type.
 */
typedef void (*OvStoragePlugin_StreamDropFn)(void *state);

/**
 * Plugin-emitted iterator yielding `AuthEvent`s. `state` is opaque
 * plugin-owned data; `next_fn` and `drop_fn` are non-null.
 */
typedef struct {
  void *state;
  OvStoragePlugin_AuthEventNextFn next_fn;
  OvStoragePlugin_StreamDropFn drop_fn;
} OvStoragePlugin_AuthEventStream;

/**
 * `next_fn` signature for [`BackendChangeStream`].
 */
typedef OvStoragePlugin_StreamStep (*OvStoragePlugin_BackendChangeNextFn)(void *state,
                                                                          OvStoragePlugin_BackendChangeEvent *out_item,
                                                                          OvStoragePlugin_Error *out_error);

/**
 * Plugin-emitted iterator over `Result<BackendChangeEvent>`.
 */
typedef struct {
  void *state;
  OvStoragePlugin_BackendChangeNextFn next_fn;
  OvStoragePlugin_StreamDropFn drop_fn;
} OvStoragePlugin_BackendChangeStream;

/**
 * Per-root entry inside [`BackendInstance::address_roots`]. Capabilities
 * are stamped onto each `Route` from this struct, so per-route gating
 * reflects the plugin's per-root advertisement.
 */
typedef struct {
  OvStoragePlugin_Str address;
  OvStoragePlugin_Capabilities capabilities;
} OvStoragePlugin_AddressRootEntry;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_AddressRootEntry *ptr;
  size_t len;
} OvStoragePlugin_List_AddressRootEntry;

/**
 * One frame in a [`BackendAddressRootsStream`]. All three variants
 * carry the same payload shape — a list of address-root entries —
 * so a single discriminated struct (no MaybeUninit union) suffices.
 */
typedef struct {
  OvStoragePlugin_BackendAddressRootsChangeTag tag;
  OvStoragePlugin_List_AddressRootEntry roots;
} OvStoragePlugin_BackendAddressRootsChange;

/**
 * `next_fn` signature for [`BackendAddressRootsStream`].
 */
typedef OvStoragePlugin_StreamStep (*OvStoragePlugin_BackendAddressRootsNextFn)(void *state,
                                                                                OvStoragePlugin_BackendAddressRootsChange *out_item,
                                                                                OvStoragePlugin_Error *out_error);

/**
 * Plugin-emitted iterator over `Result<BackendAddressRootsChange>`.
 * Address-root deltas are coarse-grained and infrequent; the host
 * drives the iterator from a per-connection task that wakes on each
 * pushed frame.
 */
typedef struct {
  void *state;
  OvStoragePlugin_BackendAddressRootsNextFn next_fn;
  OvStoragePlugin_StreamDropFn drop_fn;
} OvStoragePlugin_BackendAddressRootsStream;

/**
 * Backend identifier. Opaque to most consumers; UTF-8-encoded so it
 * can survive any tracing pipeline.
 */
typedef struct {
  OvStoragePlugin_Str id;
} OvStoragePlugin_BackendId;

/**
 * `drop` slot common to both backend and factory vtables.
 */
typedef void (*OvStoragePlugin_VTableDropFn)(void *state);

/**
 * Resolved target: the address the plugin should act on plus the
 * backend instance the dispatcher selected.
 */
typedef struct {
  OvStoragePlugin_BackendId backend_id;
  OvStoragePlugin_Str resolved_address;
} OvStoragePlugin_ResolvedTarget;

/**
 * `StatOptions` shadow shape. Every options struct starts with a
 * `struct_size` prefix; receivers validate `>= size_of::<T>()`
 * before reading tail fields.
 */
typedef struct {
  size_t struct_size;
  bool full_metadata;
} OvStoragePlugin_StatOptions;

/**
 * Cross-FFI cancellation token handle. `Copy`-passable by value;
 * `state` carries refcount semantics (clone+drop in pairs).
 * Function-pointer slots are statically linked.
 */
typedef struct {
  const OvStoragePlugin_AtomicCancelState *state;
  bool (*is_canceled)(const OvStoragePlugin_AtomicCancelState*);
  uint64_t (*register_callback)(const OvStoragePlugin_AtomicCancelState*,
                                void (*cb)(void*),
                                void *user_data);
  void (*unregister_callback)(const OvStoragePlugin_AtomicCancelState*, uint64_t sub_id);
  const OvStoragePlugin_AtomicCancelState *(*clone)(const OvStoragePlugin_AtomicCancelState*);
  void (*drop)(const OvStoragePlugin_AtomicCancelState*);
} OvStoragePlugin_CancelTokenFFI;

/**
 * Normalized checksum algorithm token (e.g. `"sha256"`, `"crc32c"`).
 * The marshalling layer enforces validation rules on the way in.
 */
typedef struct {
  OvStoragePlugin_Str token;
} OvStoragePlugin_ChecksumAlgorithm;

/**
 * One `(algorithm, bytes)` checksum entry. Field sites embed
 * `List<ChecksumEntry>` directly rather than via a `ChecksumSet`
 * alias — cbindgen 0.27 forward-declares such aliases incompletely
 * when the inner type is processed later in the emission walk.
 */
typedef struct {
  OvStoragePlugin_ChecksumAlgorithm algorithm;
  OvStoragePlugin_Bytes bytes;
} OvStoragePlugin_ChecksumEntry;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_ChecksumEntry *ptr;
  size_t len;
} OvStoragePlugin_List_ChecksumEntry;

/**
 * Permission bitset. `READ = 1<<0`, `WRITE = 1<<1`, `DELETE = 1<<2`,
 * `UPDATE_METADATA = 1<<3`. Consumers ignore unknown bits (forward-compat).
 */
typedef struct {
  uint32_t bits;
} OvStoragePlugin_EffectivePermissions;
#define OvStoragePlugin_EffectivePermissions_READ (OvStoragePlugin_EffectivePermissions){  }
#define OvStoragePlugin_EffectivePermissions_WRITE (OvStoragePlugin_EffectivePermissions){  }
#define OvStoragePlugin_EffectivePermissions_DELETE (OvStoragePlugin_EffectivePermissions){  }
#define OvStoragePlugin_EffectivePermissions_UPDATE_METADATA (OvStoragePlugin_EffectivePermissions){  }

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_EffectivePermissions value;
} OvStoragePlugin_Optional_EffectivePermissions;

/**
 * Backend-owned opaque metadata map.
 */
typedef OvStoragePlugin_KeyValueList OvStoragePlugin_SystemMetadata;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_SystemMetadata value;
} OvStoragePlugin_Optional_SystemMetadata;

/**
 * Caller-owned mutable metadata map.
 */
typedef OvStoragePlugin_KeyValueList OvStoragePlugin_UserMetadata;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_UserMetadata value;
} OvStoragePlugin_Optional_UserMetadata;

/**
 * Object metadata: address, kind, identity, checksums, optional
 * permissions / metadata. `mtime_unix_ms` is Unix milliseconds; ms
 * precision is the FFI-boundary clock contract.
 */
typedef struct {
  OvStoragePlugin_Str address;
  OvStoragePlugin_ObjectKindV1 kind;
  OvStoragePlugin_Optional_Str etag;
  OvStoragePlugin_Optional_Str version;
  OvStoragePlugin_Optional_u64 size;
  OvStoragePlugin_Optional_i64 mtime_unix_ms;
  OvStoragePlugin_List_ChecksumEntry checksums;
  OvStoragePlugin_Optional_EffectivePermissions effective_permissions;
  OvStoragePlugin_Optional_SystemMetadata system_metadata;
  OvStoragePlugin_Optional_UserMetadata user_metadata;
  OvStoragePlugin_Optional_Str modified_by;
} OvStoragePlugin_ObjectInfo;

/**
 * Callback for `BackendVTableV1::stat`.
 */
typedef void (*OvStoragePlugin_BackendStatCallback)(int32_t status,
                                                    OvStoragePlugin_ObjectInfo *result,
                                                    OvStoragePlugin_Error *error,
                                                    void *user_data);

/**
 * Method signature for `BackendVTableV1::stat`.
 */
typedef void (*OvStoragePlugin_BackendStatFn)(void *state,
                                              const OvStoragePlugin_ResolvedTarget *target,
                                              const OvStoragePlugin_StatOptions *opts,
                                              const OvStoragePlugin_CancelTokenFFI *cancel,
                                              OvStoragePlugin_BackendStatCallback on_complete,
                                              void *user_data);

/**
 * Half-open or closed byte range used by `ReadOptions::range`.
 *
 * `end_inclusive == None` reads through end-of-object.
 */
typedef struct {
  uint64_t start;
  OvStoragePlugin_Optional_u64 end_inclusive;
} OvStoragePlugin_ByteRange;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_ByteRange value;
} OvStoragePlugin_Optional_ByteRange;

/**
 * `ReadOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_Str if_match;
  OvStoragePlugin_Optional_ByteRange range;
} OvStoragePlugin_ReadOptions;

/**
 * Bytes-with-metadata payload of `ReadResult::Bytes`.
 */
typedef struct {
  OvStoragePlugin_Bytes bytes;
  OvStoragePlugin_ObjectInfo info;
} OvStoragePlugin_ReadResultBytes;

/**
 * Carries a path the host opens directly.
 */
typedef struct {
  OvStoragePlugin_Str path;
  OvStoragePlugin_ObjectInfo info;
} OvStoragePlugin_LocalDelegate;

/**
 * HTTP method + URL + header set. `headers` iteration order is not
 * promised; receivers needing stable order materialize it locally.
 */
typedef struct {
  OvStoragePlugin_Str method;
  OvStoragePlugin_Str url;
  OvStoragePlugin_KeyValueList headers;
} OvStoragePlugin_HttpRequest;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_ChecksumAlgorithm value;
} OvStoragePlugin_Optional_ChecksumAlgorithm;

/**
 * One `(algorithm, header_name)` binding inside
 * [`ResponseParsing::checksum_headers`]. Dedicated POD struct so
 * cbindgen emits a stable C type rather than a generic
 * `KeyValuePair`.
 */
typedef struct {
  OvStoragePlugin_ChecksumAlgorithm algorithm;
  OvStoragePlugin_Str header;
} OvStoragePlugin_ChecksumHeaderBinding;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_ChecksumHeaderBinding *ptr;
  size_t len;
} OvStoragePlugin_List_ChecksumHeaderBinding;

/**
 * Hints for how to parse a redirect response into the redirect's
 * object info (etag / version / size / mtime).
 */
typedef struct {
  OvStoragePlugin_Optional_Str etag_header;
  OvStoragePlugin_Optional_Str version_header;
  OvStoragePlugin_Optional_Str size_header;
  OvStoragePlugin_Optional_Str mtime_header;
  OvStoragePlugin_MtimeFormat mtime_format;
  OvStoragePlugin_List_Str system_metadata_headers;
  /**
   * See `crate::ResponseParsing::content_checksum_header`.
   */
  OvStoragePlugin_Optional_Str content_checksum_header;
  /**
   * See `crate::ResponseParsing::content_checksum_algorithm`.
   */
  OvStoragePlugin_Optional_ChecksumAlgorithm content_checksum_algorithm;
  /**
   * See `crate::ResponseParsing::checksum_headers`.
   */
  OvStoragePlugin_List_ChecksumHeaderBinding checksum_headers;
} OvStoragePlugin_ResponseParsing;

/**
 * Caller-requested operation set for `check_access` and the
 * authorization scope of a redirect.
 */
typedef struct {
  bool read;
  bool write;
  bool delete_;
  bool update_metadata;
} OvStoragePlugin_AccessOps;

/**
 * Authorization scope a redirect carries.
 */
typedef struct {
  OvStoragePlugin_Str physical_url_prefix;
  OvStoragePlugin_AccessOps operations;
  int64_t expires_at_unix_ms;
} OvStoragePlugin_RedirectScope;

/**
 * Read redirect — a pre-signed HTTP request the host follows
 * directly through its in-process HTTPS client.
 */
typedef struct {
  OvStoragePlugin_HttpRequest request;
  OvStoragePlugin_ResponseParsing response_parsing;
  int64_t expires_at_unix_ms;
  OvStoragePlugin_RedirectScope scope;
  OvStoragePlugin_Str audit_id;
  uint64_t policy_epoch;
} OvStoragePlugin_ReadRedirect;

/**
 * `next_fn` signature for [`BodyStream`]. Yields one chunk per call.
 * `Yielded` writes `out_chunk` (caller owns); `Failed` writes
 * `out_error` (caller owns); `Ended` writes neither.
 */
typedef OvStoragePlugin_StreamStep (*OvStoragePlugin_BodyStreamNextFn)(void *state,
                                                                       OvStoragePlugin_Bytes *out_chunk,
                                                                       OvStoragePlugin_Error *out_error);

/**
 * Plugin-consumable chunk iterator. `state` is opaque to the
 * plugin; `next_fn` and `drop_fn` are non-null. The plugin calls
 * `drop_fn` exactly once when done.
 */
typedef struct {
  void *state;
  OvStoragePlugin_BodyStreamNextFn next_fn;
  OvStoragePlugin_StreamDropFn drop_fn;
} OvStoragePlugin_BodyStream;

/**
 * Stream-with-metadata payload of `ReadResult::Stream`. Reuses the
 * `BodyStream` chunk-iterator shape; no semantic difference between
 * a streamed read and a streamed write at the chunk level.
 */
typedef struct {
  OvStoragePlugin_BodyStream stream;
  OvStoragePlugin_ObjectInfo info;
} OvStoragePlugin_ReadResultStream;

/**
 * What the plugin's `read` returned.
 */
typedef struct {
  OvStoragePlugin_ReadResultTag tag;
  OvStoragePlugin_ReadResultBytes bytes;
  OvStoragePlugin_LocalDelegate local_delegate;
  OvStoragePlugin_ReadRedirect redirect;
  OvStoragePlugin_ReadResultStream stream;
} OvStoragePlugin_ReadResult;

/**
 * Callback for `BackendVTableV1::read`.
 */
typedef void (*OvStoragePlugin_BackendReadCallback)(int32_t status,
                                                    OvStoragePlugin_ReadResult *result,
                                                    OvStoragePlugin_Error *error,
                                                    void *user_data);

/**
 * Method signature for `BackendVTableV1::read`.
 */
typedef void (*OvStoragePlugin_BackendReadFn)(void *state,
                                              const OvStoragePlugin_ResolvedTarget *target,
                                              const OvStoragePlugin_ReadOptions *opts,
                                              const OvStoragePlugin_CancelTokenFFI *cancel,
                                              OvStoragePlugin_BackendReadCallback on_complete,
                                              void *user_data);

/**
 * `IfDestExists::MatchEtag` payload.
 */
typedef struct {
  OvStoragePlugin_Str etag;
} OvStoragePlugin_IfDestExistsMatchEtag;

/**
 * Destination-side precondition for write / copy / rename. Tagged
 * union mirroring [`crate::IfDestExists`]; only the `match_etag`
 * payload is read when `tag == MatchEtag`.
 */
typedef struct {
  OvStoragePlugin_IfDestExistsTag tag;
  OvStoragePlugin_IfDestExistsMatchEtag match_etag;
} OvStoragePlugin_IfDestExistsV1;

/**
 * `WriteOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_IfDestExistsV1 if_dest;
  OvStoragePlugin_Optional_u64 size_hint;
  OvStoragePlugin_Optional_UserMetadata user_metadata;
  OvStoragePlugin_Optional_Str message;
} OvStoragePlugin_WriteOptions;

/**
 * Successful write result returned to the host.
 */
typedef struct {
  OvStoragePlugin_ObjectInfo info;
} OvStoragePlugin_WriteResult;

/**
 * Callback for `BackendVTableV1::write` and `write_stream`.
 */
typedef void (*OvStoragePlugin_BackendWriteCallback)(int32_t status,
                                                     OvStoragePlugin_WriteResult *result,
                                                     OvStoragePlugin_Error *error,
                                                     void *user_data);

/**
 * Method signature for `BackendVTableV1::write` (buffered).
 */
typedef void (*OvStoragePlugin_BackendWriteFn)(void *state,
                                               const OvStoragePlugin_ResolvedTarget *target,
                                               const OvStoragePlugin_Bytes *bytes,
                                               const OvStoragePlugin_WriteOptions *opts,
                                               const OvStoragePlugin_CancelTokenFFI *cancel,
                                               OvStoragePlugin_BackendWriteCallback on_complete,
                                               void *user_data);

/**
 * Method signature for `BackendVTableV1::write_stream`.
 */
typedef void (*OvStoragePlugin_BackendWriteStreamFn)(void *state,
                                                     const OvStoragePlugin_ResolvedTarget *target,
                                                     const OvStoragePlugin_BodyStream *body,
                                                     const OvStoragePlugin_WriteOptions *opts,
                                                     const OvStoragePlugin_CancelTokenFFI *cancel,
                                                     OvStoragePlugin_BackendWriteCallback on_complete,
                                                     void *user_data);

/**
 * Parameters of [`RedirectBodySourceTag::UserBytes`].
 */
typedef struct {
  uint64_t offset;
  uint64_t len;
} OvStoragePlugin_RedirectBodyUserBytes;

/**
 * Body to attach to a write redirect. `tag` selects the active
 * payload; non-active payloads carry safe defaults so dropping the
 * struct frees at most one allocation.
 */
typedef struct {
  OvStoragePlugin_RedirectBodySourceTag tag;
  OvStoragePlugin_RedirectBodyUserBytes user_bytes;
  OvStoragePlugin_Bytes inline_;
} OvStoragePlugin_RedirectBodySource;

/**
 * Captured-response shape for write redirects.
 */
typedef struct {
  OvStoragePlugin_List_Str headers;
  uint32_t body_max_bytes;
} OvStoragePlugin_ResultCapture;

/**
 * Write redirect — a pre-signed HTTP request the host follows; the
 * response is captured via [`ResultCapture`] and handed back to the
 * plugin in a [`RedirectResultBatch`].
 */
typedef struct {
  OvStoragePlugin_HttpRequest request;
  OvStoragePlugin_RedirectBodySource body_source;
  OvStoragePlugin_ResultCapture result_capture;
  int64_t expires_at_unix_ms;
  OvStoragePlugin_RedirectScope scope;
  OvStoragePlugin_Str audit_id;
  uint64_t policy_epoch;
} OvStoragePlugin_WriteRedirect;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_WriteRedirect *ptr;
  size_t len;
} OvStoragePlugin_List_WriteRedirect;

/**
 * Batch of write redirects + an opaque plugin-owned continuation
 * blob the host echoes back into `continue_write`.
 */
typedef struct {
  OvStoragePlugin_Bytes continuation;
  OvStoragePlugin_List_WriteRedirect redirects;
} OvStoragePlugin_WriteRedirectBatch;

/**
 * Callback for `BackendVTableV1::write_redirect`.
 */
typedef void (*OvStoragePlugin_BackendWriteRedirectCallback)(int32_t status,
                                                             OvStoragePlugin_WriteRedirectBatch *result,
                                                             OvStoragePlugin_Error *error,
                                                             void *user_data);

/**
 * Method signature for `BackendVTableV1::write_redirect`.
 */
typedef void (*OvStoragePlugin_BackendWriteRedirectFn)(void *state,
                                                       const OvStoragePlugin_ResolvedTarget *target,
                                                       const OvStoragePlugin_WriteOptions *opts,
                                                       const OvStoragePlugin_CancelTokenFFI *cancel,
                                                       OvStoragePlugin_BackendWriteRedirectCallback on_complete,
                                                       void *user_data);

/**
 * Captured result of a single redirect's HTTP response.
 */
typedef struct {
  uint16_t status_code;
  OvStoragePlugin_KeyValueList captured_headers;
  OvStoragePlugin_Bytes captured_body;
} OvStoragePlugin_RedirectResult;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_RedirectResult *ptr;
  size_t len;
} OvStoragePlugin_List_RedirectResult;

/**
 * Cardinality-matched result batch corresponding to a
 * [`WriteRedirectBatch`].
 */
typedef struct {
  OvStoragePlugin_List_RedirectResult results;
} OvStoragePlugin_RedirectResultBatch;

/**
 * What the plugin's `write` / `continue_write` returned this turn.
 */
typedef struct {
  OvStoragePlugin_WriteStepTag tag;
  OvStoragePlugin_WriteResult done;
  OvStoragePlugin_WriteRedirectBatch redirects;
} OvStoragePlugin_WriteStep;

/**
 * Callback for `BackendVTableV1::continue_write` and `copy`.
 */
typedef void (*OvStoragePlugin_BackendWriteStepCallback)(int32_t status,
                                                         OvStoragePlugin_WriteStep *result,
                                                         OvStoragePlugin_Error *error,
                                                         void *user_data);

/**
 * Method signature for `BackendVTableV1::continue_write`.
 */
typedef void (*OvStoragePlugin_BackendContinueWriteFn)(void *state,
                                                       const OvStoragePlugin_ResolvedTarget *target,
                                                       const OvStoragePlugin_WriteRedirectBatch *redirects,
                                                       const OvStoragePlugin_RedirectResultBatch *results,
                                                       const OvStoragePlugin_CancelTokenFFI *cancel,
                                                       OvStoragePlugin_BackendWriteStepCallback on_complete,
                                                       void *user_data);

/**
 * `DeleteOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_Str if_match;
} OvStoragePlugin_DeleteOptions;

/**
 * Callback for unit-shape methods (`delete`, `delete_directory`,
 * `rename`, factory `update_credentials`).
 */
typedef void (*OvStoragePlugin_BackendUnitCallback)(int32_t status,
                                                    OvStoragePlugin_Error *error,
                                                    void *user_data);

/**
 * Method signature for `BackendVTableV1::delete`.
 */
typedef void (*OvStoragePlugin_BackendDeleteFn)(void *state,
                                                const OvStoragePlugin_ResolvedTarget *target,
                                                const OvStoragePlugin_DeleteOptions *opts,
                                                const OvStoragePlugin_CancelTokenFFI *cancel,
                                                OvStoragePlugin_BackendUnitCallback on_complete,
                                                void *user_data);

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  uint32_t value;
} OvStoragePlugin_Optional_u32;

/**
 * `ListOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  bool recursive;
  OvStoragePlugin_Optional_u32 max_results;
  OvStoragePlugin_Optional_Str page_token;
  bool full_metadata;
} OvStoragePlugin_ListOptions;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_ObjectInfo *ptr;
  size_t len;
} OvStoragePlugin_List_ObjectInfo;

/**
 * Callback for `BackendVTableV1::list`.
 */
typedef void (*OvStoragePlugin_BackendListCallback)(int32_t status,
                                                    OvStoragePlugin_List_ObjectInfo *result,
                                                    OvStoragePlugin_Error *error,
                                                    void *user_data);

/**
 * Method signature for `BackendVTableV1::list`.
 */
typedef void (*OvStoragePlugin_BackendListFn)(void *state,
                                              const OvStoragePlugin_ResolvedTarget *prefix,
                                              const OvStoragePlugin_ListOptions *opts,
                                              const OvStoragePlugin_CancelTokenFFI *cancel,
                                              OvStoragePlugin_BackendListCallback on_complete,
                                              void *user_data);

/**
 * `ListVersionsOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_u32 max_results;
  OvStoragePlugin_Optional_Str page_token;
} OvStoragePlugin_ListVersionsOptions;

/**
 * Callback for `BackendVTableV1::list_versions`.
 */
typedef void (*OvStoragePlugin_BackendListVersionsCallback)(int32_t status,
                                                            OvStoragePlugin_List_ObjectInfo *result,
                                                            OvStoragePlugin_Error *error,
                                                            void *user_data);

/**
 * Method signature for `BackendVTableV1::list_versions`.
 */
typedef void (*OvStoragePlugin_BackendListVersionsFn)(void *state,
                                                      const OvStoragePlugin_ResolvedTarget *target,
                                                      const OvStoragePlugin_ListVersionsOptions *opts,
                                                      const OvStoragePlugin_CancelTokenFFI *cancel,
                                                      OvStoragePlugin_BackendListVersionsCallback on_complete,
                                                      void *user_data);

/**
 * Callback for `BackendVTableV1::get_latest_version`.
 */
typedef void (*OvStoragePlugin_BackendGetLatestVersionCallback)(int32_t status,
                                                                OvStoragePlugin_ObjectInfo *result,
                                                                OvStoragePlugin_Error *error,
                                                                void *user_data);

/**
 * Method signature for `BackendVTableV1::get_latest_version`.
 */
typedef void (*OvStoragePlugin_BackendGetLatestVersionFn)(void *state,
                                                          const OvStoragePlugin_ResolvedTarget *target,
                                                          const OvStoragePlugin_CancelTokenFFI *cancel,
                                                          OvStoragePlugin_BackendGetLatestVersionCallback on_complete,
                                                          void *user_data);

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_WatchDirectoryCursor value;
} OvStoragePlugin_Optional_WatchDirectoryCursor;

/**
 * `WatchDirectoryOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  bool recursive;
  bool include_metadata_changes;
  OvStoragePlugin_Optional_WatchDirectoryCursor since;
  uint64_t poll_interval_ms;
} OvStoragePlugin_WatchDirectoryOptions;

/**
 * Callback for `BackendVTableV1::watch_directory`.
 */
typedef void (*OvStoragePlugin_BackendWatchDirectoryCallback)(int32_t status,
                                                              OvStoragePlugin_BackendChangeStream *result,
                                                              OvStoragePlugin_Error *error,
                                                              void *user_data);

/**
 * Method signature for `BackendVTableV1::watch_directory`.
 */
typedef void (*OvStoragePlugin_BackendWatchDirectoryFn)(void *state,
                                                        const OvStoragePlugin_ResolvedTarget *prefix,
                                                        const OvStoragePlugin_WatchDirectoryOptions *opts,
                                                        const OvStoragePlugin_CancelTokenFFI *cancel,
                                                        OvStoragePlugin_BackendWatchDirectoryCallback on_complete,
                                                        void *user_data);

/**
 * `CreateDirectoryOptions` shadow shape. `_reserved` keeps the
 * struct non-zero-size today; set to `0`.
 */
typedef struct {
  size_t struct_size;
  uint32_t _reserved;
} OvStoragePlugin_CreateDirectoryOptions;

/**
 * Per-backend item metadata. `mtime_unix_ms` is Unix milliseconds; ms
 * precision is the FFI-boundary clock contract.
 */
typedef struct {
  OvStoragePlugin_ObjectKindV1 kind;
  OvStoragePlugin_Optional_Str etag;
  OvStoragePlugin_Optional_Str version;
  OvStoragePlugin_Optional_u64 size;
  OvStoragePlugin_Optional_i64 mtime_unix_ms;
  OvStoragePlugin_List_ChecksumEntry checksums;
  OvStoragePlugin_Optional_EffectivePermissions effective_permissions;
  OvStoragePlugin_Optional_SystemMetadata system_metadata;
  OvStoragePlugin_Optional_UserMetadata user_metadata;
  OvStoragePlugin_Optional_Str modified_by;
} OvStoragePlugin_BackendItemInfo;

/**
 * Callback for `BackendVTableV1::create_directory` and
 * `update_metadata` — both produce a `BackendItemInfo`.
 */
typedef void (*OvStoragePlugin_BackendItemInfoCallback)(int32_t status,
                                                        OvStoragePlugin_BackendItemInfo *result,
                                                        OvStoragePlugin_Error *error,
                                                        void *user_data);

/**
 * Method signature for `BackendVTableV1::create_directory`.
 */
typedef void (*OvStoragePlugin_BackendCreateDirectoryFn)(void *state,
                                                         const OvStoragePlugin_ResolvedTarget *target,
                                                         const OvStoragePlugin_CreateDirectoryOptions *opts,
                                                         const OvStoragePlugin_CancelTokenFFI *cancel,
                                                         OvStoragePlugin_BackendItemInfoCallback on_complete,
                                                         void *user_data);

/**
 * `DeleteDirectoryOptions` shadow shape. `_reserved` keeps the
 * struct non-zero-size today; set to `0`.
 */
typedef struct {
  size_t struct_size;
  uint32_t _reserved;
} OvStoragePlugin_DeleteDirectoryOptions;

/**
 * Method signature for `BackendVTableV1::delete_directory`.
 */
typedef void (*OvStoragePlugin_BackendDeleteDirectoryFn)(void *state,
                                                         const OvStoragePlugin_ResolvedTarget *target,
                                                         const OvStoragePlugin_DeleteDirectoryOptions *opts,
                                                         const OvStoragePlugin_CancelTokenFFI *cancel,
                                                         OvStoragePlugin_BackendUnitCallback on_complete,
                                                         void *user_data);

/**
 * `CopyOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_Str if_source;
  OvStoragePlugin_IfDestExistsV1 if_dest;
  OvStoragePlugin_Optional_Str message;
} OvStoragePlugin_CopyOptions;

/**
 * Method signature for `BackendVTableV1::copy`.
 */
typedef void (*OvStoragePlugin_BackendCopyFn)(void *state,
                                              const OvStoragePlugin_ResolvedTarget *src,
                                              const OvStoragePlugin_ResolvedTarget *dest,
                                              const OvStoragePlugin_CopyOptions *opts,
                                              const OvStoragePlugin_CancelTokenFFI *cancel,
                                              OvStoragePlugin_BackendWriteStepCallback on_complete,
                                              void *user_data);

/**
 * `RenameOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_Str if_source;
  OvStoragePlugin_IfDestExistsV1 if_dest;
  OvStoragePlugin_Optional_Str message;
} OvStoragePlugin_RenameOptions;

/**
 * Method signature for `BackendVTableV1::rename`.
 */
typedef void (*OvStoragePlugin_BackendRenameFn)(void *state,
                                                const OvStoragePlugin_ResolvedTarget *src,
                                                const OvStoragePlugin_ResolvedTarget *dest,
                                                const OvStoragePlugin_RenameOptions *opts,
                                                const OvStoragePlugin_CancelTokenFFI *cancel,
                                                OvStoragePlugin_BackendUnitCallback on_complete,
                                                void *user_data);

/**
 * `UpdateMetadataOptions` shadow shape.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_Optional_Str if_match;
  bool allow_rewrite_emulation;
  OvStoragePlugin_KeyValueList user_metadata_set;
  OvStoragePlugin_List_Str user_metadata_remove;
  OvStoragePlugin_Optional_Str message;
} OvStoragePlugin_UpdateMetadataOptions;

/**
 * Method signature for `BackendVTableV1::update_metadata`.
 */
typedef void (*OvStoragePlugin_BackendUpdateMetadataFn)(void *state,
                                                        const OvStoragePlugin_ResolvedTarget *target,
                                                        const OvStoragePlugin_UpdateMetadataOptions *opts,
                                                        const OvStoragePlugin_CancelTokenFFI *cancel,
                                                        OvStoragePlugin_BackendItemInfoCallback on_complete,
                                                        void *user_data);

/**
 * Authorization decision returned by `StorageBackend::check_access`.
 */
typedef struct {
  bool allowed;
  OvStoragePlugin_AccessOps denied_ops;
  OvStoragePlugin_Optional_Str reason;
} OvStoragePlugin_AccessDecision;

/**
 * Callback for `BackendVTableV1::check_access`.
 */
typedef void (*OvStoragePlugin_BackendCheckAccessCallback)(int32_t status,
                                                           OvStoragePlugin_AccessDecision *result,
                                                           OvStoragePlugin_Error *error,
                                                           void *user_data);

/**
 * Method signature for `BackendVTableV1::check_access`.
 */
typedef void (*OvStoragePlugin_BackendCheckAccessFn)(void *state,
                                                     const OvStoragePlugin_ResolvedTarget *target,
                                                     const OvStoragePlugin_AccessOps *ops,
                                                     const OvStoragePlugin_CancelTokenFFI *cancel,
                                                     OvStoragePlugin_BackendCheckAccessCallback on_complete,
                                                     void *user_data);

/**
 * Callback for `BackendVTableV1::watch_address_roots`.
 */
typedef void (*OvStoragePlugin_BackendWatchAddressRootsCallback)(int32_t status,
                                                                 OvStoragePlugin_BackendAddressRootsStream *result,
                                                                 OvStoragePlugin_Error *error,
                                                                 void *user_data);

/**
 * Method signature for `BackendVTableV1::watch_address_roots`.
 */
typedef void (*OvStoragePlugin_BackendWatchAddressRootsFn)(void *state,
                                                           const OvStoragePlugin_CancelTokenFFI *cancel,
                                                           OvStoragePlugin_BackendWatchAddressRootsCallback on_complete,
                                                           void *user_data);

/**
 * Vtable for one configured backend instance. The host dispatches
 * object operations through these function-pointer slots.
 *
 * `drop` is synchronous; other slots are async per the calling
 * convention at the top of this section.
 *
 * Forward compatibility: `struct_size` must cover at least the v1
 * fields. The trailing 16 `_reserved` slots are zero-initialized so
 * a newer host running an older plugin sees `None` for unimplemented
 * methods. New SPI methods consume the next free reserved slot in
 * tree order; existing fields never reorder.
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_VTableDropFn drop;
  OvStoragePlugin_BackendStatFn stat;
  OvStoragePlugin_BackendReadFn read;
  OvStoragePlugin_BackendWriteFn write;
  OvStoragePlugin_BackendWriteStreamFn write_stream;
  OvStoragePlugin_BackendWriteRedirectFn write_redirect;
  OvStoragePlugin_BackendContinueWriteFn continue_write;
  OvStoragePlugin_BackendDeleteFn delete_;
  OvStoragePlugin_BackendListFn list;
  OvStoragePlugin_BackendListVersionsFn list_versions;
  OvStoragePlugin_BackendGetLatestVersionFn get_latest_version;
  OvStoragePlugin_BackendWatchDirectoryFn watch_directory;
  OvStoragePlugin_BackendCreateDirectoryFn create_directory;
  OvStoragePlugin_BackendDeleteDirectoryFn delete_directory;
  OvStoragePlugin_BackendCopyFn copy;
  OvStoragePlugin_BackendRenameFn rename;
  OvStoragePlugin_BackendUpdateMetadataFn update_metadata;
  OvStoragePlugin_BackendCheckAccessFn check_access;
  OvStoragePlugin_BackendWatchAddressRootsFn watch_address_roots;
  OvStoragePlugin_Error *(*_reserved[16])(void*);
} OvStoragePlugin_BackendVTableV1;

/**
 * Plugin-allocated backend state plus the backend's vtable pointer.
 * The host owns the handle until dropped, then invokes
 * `vtable->drop(state)` exactly once to release per-instance
 * resources.
 */
typedef struct {
  void *state;
  const OvStoragePlugin_BackendVTableV1 *vtable;
} OvStoragePlugin_BackendHandle;

/**
 * Configured backend instance returned by
 * `BackendFactoryVTableV1::instantiate`. Dropping the instance
 * cascades through `BackendHandle`'s drop, which invokes the
 * plugin's `drop` slot to release per-instance state.
 */
typedef struct {
  OvStoragePlugin_BackendId backend_id;
  OvStoragePlugin_BackendHandle backend;
  OvStoragePlugin_List_AddressRootEntry address_roots;
  OvStoragePlugin_Optional_Str display_name;
  OvStoragePlugin_ConnectionAuthState auth_state;
} OvStoragePlugin_BackendInstance;

/**
 * Source of bytes the host hands the plugin for `write` /
 * `write_stream`. `Stream` carries a vtable handle the plugin pulls
 * chunks from via `next_fn`.
 */
typedef struct {
  OvStoragePlugin_BodyTag tag;
  OvStoragePlugin_Bytes bytes;
  OvStoragePlugin_Str local_file;
  OvStoragePlugin_BodyStream stream;
} OvStoragePlugin_Body;

/**
 * Enum-field choice list source.
 */
typedef struct {
  OvStoragePlugin_EnumSourceTag tag;
  OvStoragePlugin_List_Str static_choices;
} OvStoragePlugin_EnumSource;

/**
 * `ConfigField`'s kind. The `Enum` variant carries an [`EnumSource`].
 */
typedef struct {
  OvStoragePlugin_ConfigFieldKindTag tag;
  OvStoragePlugin_EnumSource enum_source;
} OvStoragePlugin_ConfigFieldKind;

/**
 * Configuration value carried by a [`ConnectionRequest::config`]
 * entry. Top-level TOML scalars use the matching variant; tables and
 * arrays arrive as `Toml` (reserialized to a TOML string).
 */
typedef struct {
  OvStoragePlugin_ConfigValueTag tag;
  OvStoragePlugin_Str string_value;
  int64_t int_value;
  bool bool_value;
  OvStoragePlugin_Str toml_value;
} OvStoragePlugin_ConfigValue;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_ConfigValue value;
} OvStoragePlugin_Optional_ConfigValue;

/**
 * One configuration-schema field of a backend kind descriptor.
 */
typedef struct {
  OvStoragePlugin_Str key;
  OvStoragePlugin_Str display_name;
  OvStoragePlugin_ConfigFieldKind kind;
  bool required;
  OvStoragePlugin_Optional_ConfigValue default_;
  OvStoragePlugin_Optional_Str help;
  OvStoragePlugin_Optional_Str example;
  OvStoragePlugin_Optional_Str group;
  bool advanced;
} OvStoragePlugin_ConfigField;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_ConfigField *ptr;
  size_t len;
} OvStoragePlugin_List_ConfigField;

/**
 * One credential-schema field of a backend kind descriptor.
 */
typedef struct {
  OvStoragePlugin_Str key;
  OvStoragePlugin_Str display_name;
  /**
   * Per-method default (literal or `${NAME}` template). See
   * `types::CredentialField::default`.
   */
  OvStoragePlugin_Optional_Str default_;
  OvStoragePlugin_Optional_Str help;
  bool advanced;
} OvStoragePlugin_CredentialField;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_CredentialField *ptr;
  size_t len;
} OvStoragePlugin_List_CredentialField;

/**
 * Named credential entry-point referenced by a backend descriptor.
 * `fields` keys index into the descriptor's `credential_schema`.
 */
typedef struct {
  OvStoragePlugin_Str key;
  OvStoragePlugin_Str display_name;
  OvStoragePlugin_List_Str fields;
  OvStoragePlugin_Optional_Str help;
  bool advanced;
} OvStoragePlugin_CredentialMethod;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_CredentialMethod *ptr;
  size_t len;
} OvStoragePlugin_List_CredentialMethod;

/**
 * Optional `T`. `present == true` means `value` is initialized;
 * otherwise `value` carries unspecified bytes and must not be read.
 * cbindgen emits a distinct C type per concrete `T`.
 */
typedef struct {
  bool present;
  OvStoragePlugin_Bytes value;
} OvStoragePlugin_Optional_Bytes;

/**
 * Backend-kind descriptor.
 */
typedef struct {
  OvStoragePlugin_Str kind;
  OvStoragePlugin_Str display_name;
  OvStoragePlugin_Optional_Str description;
  OvStoragePlugin_List_ConfigField config_schema;
  OvStoragePlugin_List_CredentialField credential_schema;
  OvStoragePlugin_List_CredentialMethod credential_methods;
  OvStoragePlugin_Optional_Bytes icon;
  bool supports_runtime_add;
} OvStoragePlugin_StorageBackendKindDescriptor;

/**
 * `(key, ConfigValue)` entry inside a [`ConnectionRequest::config`]
 * list. Iteration order is not preserved.
 */
typedef struct {
  OvStoragePlugin_Str key;
  OvStoragePlugin_ConfigValue value;
} OvStoragePlugin_ConnectionConfigEntry;

/**
 * Owned homogeneous list of `T`. `ptr` points at exactly `len`
 * elements (capacity == len). Empty lists use a one-element
 * sentinel allocation. cbindgen emits a distinct C type per
 * concrete `T` (e.g. `OvStorageListObjectInfo`).
 */
typedef struct {
  OvStoragePlugin_ConnectionConfigEntry *ptr;
  size_t len;
} OvStoragePlugin_List_ConnectionConfigEntry;

/**
 * Connection-create request. `config` is a flat key/value list;
 * top-level scalars use the matching `ConfigValue` variant, nested
 * values arrive as `ConfigValue::Toml`.
 */
typedef struct {
  OvStoragePlugin_Str backend_kind;
  OvStoragePlugin_List_ConnectionConfigEntry config;
  OvStoragePlugin_SecretBundle credentials;
  bool persist;
  OvStoragePlugin_Optional_Str display_name;
} OvStoragePlugin_ConnectionRequest;

/**
 * Status code returned to `on_complete` callbacks. `0`
 * ([`FFI_STATUS_OK`]) is reserved for success; errors return
 * [`FFI_STATUS_ERR`] (`-1`) and carry the real `ErrorCode` on the
 * `*mut Error`. Reserving `0` avoids a collision with
 * `ErrorCode::NotFound` (also discriminant `0`).
 */
typedef int32_t OvStoragePlugin_FfiStatus;

/**
 * Static plugin manifest exported by backend plugins as
 * `ovstorage_plugin_manifest_v1`. The pointed-at memory is owned by
 * the plugin binary and lives for the lifetime of the loaded
 * library; the host never frees a manifest.
 *
 * Authz plugins export an analogous symbol
 * (`ovstorage_authz_plugin_manifest_v1`); each domain's loader
 * resolves its own symbol name.
 */
typedef struct {
  size_t struct_size;
  uint32_t abi_version;
  const char *name;
  const char *version;
  /**
   * Test-fixture marker. Production hosts (`allow_test_plugins =
   * false`) refuse to load `test_only = true` plugins and surface
   * `ErrorCode::PluginRejected`. Older plugins whose manifest
   * predates this field default to `false` via the `struct_size`
   * forward-compatibility rule.
   */
  bool test_only;
} OvStoragePlugin_PluginManifestV1;

/**
 * Sync-getter signature for `BackendFactoryVTableV1::descriptor`.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_FactoryDescriptorFn)(void *factory_state,
                                                                      OvStoragePlugin_StorageBackendKindDescriptor *out);

/**
 * Callback for `BackendFactoryVTableV1::instantiate`.
 */
typedef void (*OvStoragePlugin_FactoryInstantiateCallback)(int32_t status,
                                                           OvStoragePlugin_BackendInstance *result,
                                                           OvStoragePlugin_Error *error,
                                                           void *user_data);

/**
 * Method signature for `BackendFactoryVTableV1::instantiate`.
 */
typedef void (*OvStoragePlugin_FactoryInstantiateFn)(void *factory_state,
                                                     const OvStoragePlugin_ConnectionRequest *request,
                                                     const OvStoragePlugin_CancelTokenFFI *cancel,
                                                     OvStoragePlugin_FactoryInstantiateCallback on_complete,
                                                     void *user_data);

/**
 * Method signature for `BackendFactoryVTableV1::update_credentials`.
 */
typedef void (*OvStoragePlugin_FactoryUpdateCredentialsFn)(void *factory_state,
                                                           const OvStoragePlugin_Connection *connection,
                                                           const OvStoragePlugin_SecretBundle *credentials,
                                                           const OvStoragePlugin_CancelTokenFFI *cancel,
                                                           OvStoragePlugin_BackendUnitCallback on_complete,
                                                           void *user_data);

/**
 * Callback for `BackendFactoryVTableV1::authenticate`.
 */
typedef void (*OvStoragePlugin_FactoryAuthenticateCallback)(int32_t status,
                                                            OvStoragePlugin_AuthEventStream *result,
                                                            OvStoragePlugin_Error *error,
                                                            void *user_data);

/**
 * Method signature for `BackendFactoryVTableV1::authenticate`.
 * `capability` is the host's declared interactive-auth surface; the
 * plugin uses it to pick PKCE vs. device flow vs. fail-fast.
 */
typedef void (*OvStoragePlugin_FactoryAuthenticateFn)(void *factory_state,
                                                      const OvStoragePlugin_Connection *connection,
                                                      OvStoragePlugin_InteractiveAuthCapabilityV1 capability,
                                                      const OvStoragePlugin_CancelTokenFFI *cancel,
                                                      OvStoragePlugin_FactoryAuthenticateCallback on_complete,
                                                      void *user_data);

/**
 * Vtable for one storage-backend factory. The host drives connection
 * management through these slots and reaches individual
 * `BackendInstance`s via `instantiate`. Forward-compat reserved
 * slots: see [`BackendVTableV1`].
 */
typedef struct {
  size_t struct_size;
  OvStoragePlugin_VTableDropFn drop;
  OvStoragePlugin_FactoryDescriptorFn descriptor;
  OvStoragePlugin_FactoryInstantiateFn instantiate;
  OvStoragePlugin_FactoryUpdateCredentialsFn update_credentials;
  OvStoragePlugin_FactoryAuthenticateFn authenticate;
  OvStoragePlugin_Error *(*_reserved[16])(void*);
} OvStoragePlugin_BackendFactoryVTableV1;

/**
 * Result returned by `ovstorage_plugin_init_v1` (the backend init
 * entry point). Vtable storage lives inside the plugin binary; the
 * host borrows the pointer for the lifetime of the loaded library.
 *
 * Banded ABI handshake: `abi_version` is the canonical version the
 * plugin was compiled against; `[min_supported_abi_version,
 * max_supported_abi_version]` is the inclusive band the plugin's
 * vtable supports. The host validates `min <= host.abi_version <=
 * max`; mismatch surfaces as `ErrorCode::IncompatibleType`.
 * Width-1 bands set both equal to `abi_version`.
 */
typedef struct {
  size_t struct_size;
  uint32_t abi_version;
  /**
   * Inclusive lower bound of host ABI versions the plugin
   * supports. Hosts with `abi_version < min` reject the plugin.
   */
  uint32_t min_supported_abi_version;
  /**
   * Inclusive upper bound of host ABI versions the plugin
   * supports. Hosts with `abi_version > max` reject the plugin.
   */
  uint32_t max_supported_abi_version;
  /**
   * Plugin-allocated state passed verbatim to every vtable method.
   * Released by the vtable's `drop` slot.
   */
  void *plugin_state;
  /**
   * Pointer to the plugin's static [`BackendFactoryVTableV1`].
   */
  const OvStoragePlugin_BackendFactoryVTableV1 *factory_vtable;
} OvStoragePlugin_BackendPluginInitResultV1;

/**
 * Composite key for `HostCallbacks::keyring_*` (
 * `(backend_kind, connection_id, field) → SecretBytes`).
 */
typedef struct {
  OvStoragePlugin_Str backend_kind;
  OvStoragePlugin_ConnectionId connection_id;
  OvStoragePlugin_Str field;
} OvStoragePlugin_KeyringKey;

/**
 * `keyring_get` callback. Writes `Optional::some(value)` on hit,
 * `Optional::none()` on miss; returns a non-null `Error` on
 * host-side keyring failure.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_HostKeyringGetFn)(void *host_state,
                                                                   const OvStoragePlugin_KeyringKey *key,
                                                                   OvStoragePlugin_Optional_SecretBytes *out_value);

/**
 * `keyring_put` callback.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_HostKeyringPutFn)(void *host_state,
                                                                   const OvStoragePlugin_KeyringKey *key,
                                                                   const OvStoragePlugin_SecretBytes *value);

/**
 * `keyring_delete` callback.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_HostKeyringDeleteFn)(void *host_state,
                                                                      const OvStoragePlugin_KeyringKey *key);

/**
 * Function the host calls (at most once) inside
 * `auth_refresh_lock_with_refresh` while holding the per-
 * `(backend_kind, connection_id)` file lock.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_HostRefreshFn)(void *refresh_state);

/**
 * `auth_refresh_lock_with_refresh` callback. The host acquires the
 * per-`(backend_kind, connection_id)` lock, re-checks freshness
 * against `freshness_window_ms`, and invokes `refresh_fn` only when
 * the snapshot is stale.
 */
typedef OvStoragePlugin_Error *(*OvStoragePlugin_HostAuthRefreshLockFn)(void *host_state,
                                                                        const OvStoragePlugin_Str *backend_kind,
                                                                        const OvStoragePlugin_ConnectionId *connection_id,
                                                                        uint64_t freshness_window_ms,
                                                                        void *refresh_state,
                                                                        OvStoragePlugin_HostRefreshFn refresh_fn);

/**
 * Plugin-to-host log forwarding. Plugins (in any language) call this
 * to emit one log event into the host's logging pipeline; the host
 * applies its own filter/format/sink. `target` typically names the
 * emitting subsystem (e.g. `"ovstorage_plugin_nucleus::handshake"`);
 * `message` is the rendered text. Both strings borrowed for the call.
 */
typedef void (*OvStoragePlugin_HostLogFn)(void *host_state,
                                          uint8_t level,
                                          const OvStoragePlugin_Str *target,
                                          const OvStoragePlugin_Str *message);

/**
 * Function-pointer table the host hands the plugin once at load
 * time. `host_state` is opaque context the plugin threads verbatim
 * through every callback. Future additions append after the v1
 * fields and bump `struct_size`; plugins refuse callbacks beyond
 * the host's declared surface.
 */
typedef struct {
  size_t struct_size;
  void *host_state;
  OvStoragePlugin_HostKeyringGetFn keyring_get;
  OvStoragePlugin_HostKeyringPutFn keyring_put;
  OvStoragePlugin_HostKeyringDeleteFn keyring_delete;
  OvStoragePlugin_HostAuthRefreshLockFn auth_refresh_lock_with_refresh;
  /**
   * Identifies the kind of host loading the plugin. Plugins with
   * configurations unsafe in multi-tenant deployments (e.g.
   * `file://` rooted at `/`) inspect this and may return
   * `ErrorCode::Unsupported` from `instantiate`.
   *
   * Encoded as `u32` (not an enum) so unknown future values can
   * be treated as "newer host kind" rather than an error.
   * Values: 0 = Library, 1 = Broker. See [`HostKindV1`].
   */
  uint32_t host_kind;
  /**
   * Forwards a single log event from the plugin into the host's
   * logging pipeline. Plugins compiled against an older header
   * where this field doesn't exist must check `struct_size` before
   * reading it.
   */
  OvStoragePlugin_HostLogFn log;
} OvStoragePlugin_HostCallbacks;

#define OvStoragePlugin_FFI_STATUS_OK 0

#define OvStoragePlugin_FFI_STATUS_ERR -1

/**
 * Drop a [`BackendChangeEvent`]'s active payload in place. Safe with
 * NULL. The pointee is caller-owned `out_item` storage.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`BackendChangeEvent`] produced by an ovstorage call.
 * Double-freeing is UB.
 */
void ovstorage_plugin_backend_change_event_free(OvStoragePlugin_BackendChangeEvent *value);

/**
 * Reclaim a heap-allocated [`AuthEventStream`] returned through a
 * `FactoryAuthenticateCallback`. Drives `drop_fn` exactly once
 * before releasing the outer allocation. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_auth_event_stream_free(OvStoragePlugin_AuthEventStream *value);

/**
 * Reclaim a heap-allocated [`BackendChangeStream`] returned through
 * a `BackendChangeStreamCallback`. Drives `drop_fn` exactly once
 * before releasing the outer allocation. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_backend_change_stream_free(OvStoragePlugin_BackendChangeStream *value);

/**
 * Drop a [`BackendAddressRootsChange`] in place. Safe with NULL. The
 * pointee is caller-owned `out_item` storage.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`BackendAddressRootsChange`] produced by an ovstorage call.
 * Double-freeing is UB.
 */
void ovstorage_plugin_backend_address_roots_change_free(OvStoragePlugin_BackendAddressRootsChange *value);

/**
 * Reclaim a heap-allocated [`BackendAddressRootsStream`] returned
 * through a `BackendWatchAddressRootsCallback`. Drives `drop_fn`
 * exactly once before releasing the outer allocation. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_backend_address_roots_stream_free(OvStoragePlugin_BackendAddressRootsStream *value);

/**
 * Free an [`ErrorContextV1`] previously produced by an ovstorage
 * call. Safe to call with NULL.
 *
 * Use this when host code lifts a context out of its parent
 * [`Error`] and must release it independently. The standard release
 * path (free the parent error) reaches the context automatically.
 *
 * # Safety
 *
 * `context`, when non-null, must point at a valid [`ErrorContextV1`]
 * produced by an ovstorage call.
 */
void ovstorage_plugin_error_context_free(OvStoragePlugin_ErrorContextV1 *context);

/**
 * Reclaim a heap-allocated [`Error`] returned through a callback.
 * Safe with NULL. Calling twice on the same pointer is UB.
 *
 * Caller-owned storage (e.g. an error a stream's `next_fn` writes
 * into a caller-supplied `out_error`) MUST NOT be released via this
 * function — it is not heap-allocated by this crate. Drop such
 * values in place.
 *
 * # Safety
 *
 * `error`, when non-null, must be a heap pointer produced by an
 * ovstorage call (boxed `Error`). Passing a non-boxed pointer is UB.
 */
void ovstorage_plugin_error_free(OvStoragePlugin_Error *error);

/**
 * Borrow the optional recovery hint attached to an [`Error`].
 *
 * The returned pointer is borrowed from `error` and remains valid
 * until `ovstorage_plugin_error_free` or the owner drops the error.
 * Returns `false` when no hint is present or any pointer is NULL.
 *
 * # Safety
 *
 * `error`, when non-null, must point at a valid [`Error`] produced
 * by an ovstorage call. `out_ptr` and `out_len`, when non-null, must
 * be valid writable out-parameters.
 */
bool ovstorage_plugin_error_get_next_action(const OvStoragePlugin_Error *error,
                                            const char **out_ptr,
                                            size_t *out_len);

/**
 * Reclaim a heap-allocated [`BackendInstance`] returned through a
 * `FactoryInstantiateCallback`. Drives the embedded backend's
 * `drop` slot before releasing the outer allocation. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-boxed pointer is UB.
 */
void ovstorage_plugin_backend_instance_free(OvStoragePlugin_BackendInstance *value);

/**
 * Drop a [`BackendId`]'s inner allocation in place. Safe with NULL.
 * `BackendId` is always embedded; the outer pointee is caller-owned.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`BackendId`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_backend_id_free(OvStoragePlugin_BackendId *value);

/**
 * Drop a [`ResolvedTarget`]'s nested allocations in place. Safe
 * with NULL. The pointee is caller-owned.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`ResolvedTarget`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_resolved_target_free(OvStoragePlugin_ResolvedTarget *value);

/**
 * Reclaim a heap-allocated [`ObjectInfo`] returned through a
 * `BackendStatCallback`. Safe with NULL. Do NOT call this on an
 * embedded `ObjectInfo` field — rely on the parent's destructor.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_object_info_free(OvStoragePlugin_ObjectInfo *value);

/**
 * Drop a [`BodyStream`] handle in place, driving its `drop_fn`
 * exactly once. Safe with NULL. The pointee storage is not released.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`BodyStream`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_body_stream_free(OvStoragePlugin_BodyStream *value);

/**
 * Drop a [`Body`]'s active payload in place. Safe with NULL. The
 * pointee storage is caller-owned.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`Body`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_body_free(OvStoragePlugin_Body *value);

/**
 * Reclaim a heap-allocated [`WriteResult`] returned through a
 * `BackendWriteCallback`. Safe with NULL. Do NOT call on
 * caller-owned storage — UB.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_write_result_free(OvStoragePlugin_WriteResult *value);

/**
 * Reclaim a heap-allocated [`ReadResult`] returned through a
 * `BackendReadCallback`. Safe with NULL. Do NOT call on
 * caller-owned storage — UB.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_read_result_free(OvStoragePlugin_ReadResult *value);

/**
 * Reclaim a heap-allocated [`WriteStep`] returned through a
 * `BackendWriteStepCallback`. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_write_step_free(OvStoragePlugin_WriteStep *value);

/**
 * Reclaim a heap-allocated [`AccessDecision`] returned through a
 * `BackendAccessDecisionCallback`. Safe with NULL.
 *
 * # Safety
 *
 * `value`, when non-null, must be a heap pointer produced by an
 * ovstorage call. Passing a non-heap pointer is UB.
 */
void ovstorage_plugin_access_decision_free(OvStoragePlugin_AccessDecision *value);

/**
 * Release the buffer owned by a [`Str`] in place, zeroing the
 * `Str` slot. Safe with NULL. The `Str` storage itself (the pointee)
 * is not released; only the inner allocation is freed.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`Str`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_str_free(OvStoragePlugin_Str *value);

/**
 * Release the buffer owned by a [`Bytes`] in place. Safe with NULL.
 * Same convention as `ovstorage_plugin_str_free`.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`Bytes`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_bytes_free(OvStoragePlugin_Bytes *value);

/**
 * Drop a [`StorageBackendKindDescriptor`]'s nested allocations in
 * place. Safe with NULL. The pointee is caller-owned (the
 * `descriptor` sync slot's out-parameter).
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * descriptor produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_storage_backend_kind_descriptor_free(OvStoragePlugin_StorageBackendKindDescriptor *value);

/**
 * Drop a [`ConnectionRequest`]'s nested allocations in place. Safe
 * with NULL. The pointee is caller-owned input storage.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`ConnectionRequest`] produced by an ovstorage call.
 * Double-freeing is UB.
 */
void ovstorage_plugin_connection_request_free(OvStoragePlugin_ConnectionRequest *value);

/**
 * Drop a [`Connection`]'s nested allocations in place. Safe with
 * NULL. The pointee is caller-owned (input parameter or embedded in
 * `AuthEvent::Succeeded`).
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`Connection`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_connection_free(OvStoragePlugin_Connection *value);

/**
 * Drop an [`AuthEvent`]'s active payload in place. Safe with NULL.
 * `AuthEvent` is delivered through caller-owned `out_item` storage
 * from `AuthEventStream::next_fn`.
 *
 * # Safety
 *
 * `value`, when non-null, must point at a valid, properly aligned
 * [`AuthEvent`] produced by an ovstorage call. Double-freeing is UB.
 */
void ovstorage_plugin_auth_event_free(OvStoragePlugin_AuthEvent *value);

#endif  /* OVSTORAGE_PLUGIN_H */
