/* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * ovstorage authz-plugin C ABI.
 *
 * Generated by cbindgen from crates/ovstorage-authz/src/ffi.rs.
 * Do not edit by hand: edit the Rust source and rerun `cargo build` on
 * the crate. The build script regenerates this file in-place; the file
 * is checked in for code review and IDE consumption.
 *
 * Authz plugins reuse the manifest + init + primitive types from the
 * storage plugin C ABI in `ovstorage_plugin.h` (PluginManifestV1,
 * PluginInitResultV1, OVSTORAGE_PLUGIN_ABI_VERSION, Str, List, Optional,
 * KeyValueList, ConfigValue, Error, CancelTokenFFI). The host
 * disambiguates an authz cdylib from a backend cdylib via
 * `PluginManifestV1::plugin_kind`.
 *
 * Input ownership contract for vtable methods: every `const *` input
 * parameter transfers ownership from host to plugin at the moment of
 * the call. The plugin MUST consume each input synchronously before
 * returning (typically via `memcpy`/deep-copy into plugin-owned
 * storage), because the host considers the inputs gone the instant
 * the vtable function returns and will not free them. Holding an
 * input pointer across an async boundary is undefined behavior. The
 * plugin signals completion by invoking `on_complete(status, result,
 * error, user_data)` exactly once; `result` and `error` ownership
 * transfer from plugin to host on that callback.
 */

/* The preamble (storage-SPI include + manual `List<AuthzDecisionV1>`
 * monomorphization) sits outside cbindgen's main `OVSTORAGE_AUTHZ_PLUGIN_H`
 * guard, so it needs its own guard to stay idempotent under repeated
 * `#include` of this header. Without it, the typedef below would be
 * re-emitted on every include and trip a C `conflicting types` error. */
#ifndef OVSTORAGE_AUTHZ_PLUGIN_PREAMBLE_H
#define OVSTORAGE_AUTHZ_PLUGIN_PREAMBLE_H

#include <stddef.h>
#include "ovstorage_plugin.h"

/* Local concrete instantiation of `List<AuthzDecisionV1>`. cbindgen
 * runs with `parse_deps = false` and cannot monomorphize the generic;
 * it sees the Rust alias `ListAuthzDecisionV1` as an opaque named
 * type and `[export.rename]` redirects every reference to the typedef
 * declared here. Layout matches the storage SPI's `List<T>` (ptr +
 * len). `style = "both"` emits the decision struct as
 * `typedef struct OvStorageAuthzPlugin_AuthzDecisionV1 { ... }
 * OvStorageAuthzPlugin_AuthzDecisionV1;`, so the forward struct tag
 * below is consistent with the later definition. */
struct OvStorageAuthzPlugin_AuthzDecisionV1;
typedef struct {
  struct OvStorageAuthzPlugin_AuthzDecisionV1 *ptr;
  size_t len;
} OvStorageAuthzPlugin_List_AuthzDecisionV1;

#endif /* OVSTORAGE_AUTHZ_PLUGIN_PREAMBLE_H */


#ifndef OVSTORAGE_AUTHZ_PLUGIN_H
#define OVSTORAGE_AUTHZ_PLUGIN_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C ABI version. Separate from `OVSTORAGE_PLUGIN_ABI_VERSION` so the
 * authz vtable can rev independently of the storage one.
 */
#define OVSTORAGE_AUTHZ_PLUGIN_ABI_VERSION 1

typedef enum OvStorageAuthzPlugin_AuthzEffectFFI {
  OvStorageAuthzPlugin_AuthzEffectFFI_Allow = 0,
  OvStorageAuthzPlugin_AuthzEffectFFI_Deny = 1,
} OvStorageAuthzPlugin_AuthzEffectFFI;

/**
 * Callback for `configure`; status 0 on success.
 */
typedef void (*OvStorageAuthzPlugin_AuthzConfigureCallback)(int32_t status,
                                                            OvStoragePlugin_Error *error,
                                                            void *user_data);

/**
 * `configure` method signature. `config` is a flat `(key, ConfigValue)`
 * list; `cancel` is borrowed for the call duration and must not be
 * retained past `on_complete`.
 */
typedef void (*OvStorageAuthzPlugin_AuthzConfigureFn)(void *plugin_state,
                                                      const OvStoragePlugin_List_ConnectionConfigEntry *config,
                                                      const OvStoragePlugin_CancelTokenFFI *cancel,
                                                      OvStorageAuthzPlugin_AuthzConfigureCallback on_complete,
                                                      void *user_data);

/**
 * Identity making the request.
 */
typedef struct OvStorageAuthzPlugin_PrincipalV1 {
  size_t struct_size;
  OvStoragePlugin_Str id;
  OvStoragePlugin_Optional_Str display_name;
  OvStoragePlugin_KeyValueList attributes;
  OvStoragePlugin_Optional_i64 valid_until_unix_ms;
  OvStoragePlugin_Str source;
} OvStorageAuthzPlugin_PrincipalV1;

/**
 * Request to authorize one operation against one (optional) address.
 * `operation` is a string (not an enum) so new operations land without an
 * ABI break; old plugins must default-deny on unrecognized values.
 */
typedef struct OvStorageAuthzPlugin_AuthzRequestV1 {
  size_t struct_size;
  struct OvStorageAuthzPlugin_PrincipalV1 principal;
  OvStoragePlugin_Str operation;
  OvStoragePlugin_Optional_Str address;
  uint64_t policy_epoch;
  OvStoragePlugin_Optional_Str audit_id;
} OvStorageAuthzPlugin_AuthzRequestV1;

/**
 * Decision returned by `authorize` or one entry of `filter_list_batch`.
 */
typedef struct OvStorageAuthzPlugin_AuthzDecisionV1 {
  size_t struct_size;
  enum OvStorageAuthzPlugin_AuthzEffectFFI effect;
  OvStoragePlugin_Optional_Str reason;
  OvStoragePlugin_Optional_Str explanation;
  OvStoragePlugin_Optional_u64 decision_ttl_ms;
} OvStorageAuthzPlugin_AuthzDecisionV1;

/**
 * Callback for `authorize`.
 */
typedef void (*OvStorageAuthzPlugin_AuthzAuthorizeCallback)(int32_t status,
                                                            struct OvStorageAuthzPlugin_AuthzDecisionV1 *result,
                                                            OvStoragePlugin_Error *error,
                                                            void *user_data);

/**
 * `authorize` method signature.
 */
typedef void (*OvStorageAuthzPlugin_AuthzAuthorizeFn)(void *plugin_state,
                                                      const struct OvStorageAuthzPlugin_AuthzRequestV1 *request,
                                                      const OvStoragePlugin_CancelTokenFFI *cancel,
                                                      OvStorageAuthzPlugin_AuthzAuthorizeCallback on_complete,
                                                      void *user_data);

/**
 * Callback for `filter_list_batch`; result list has one decision per
 * address in the same order.
 */
typedef void (*OvStorageAuthzPlugin_AuthzFilterCallback)(int32_t status,
                                                         OvStorageAuthzPlugin_List_AuthzDecisionV1 *result,
                                                         OvStoragePlugin_Error *error,
                                                         void *user_data);

/**
 * `filter_list_batch` method signature.
 */
typedef void (*OvStorageAuthzPlugin_AuthzFilterFn)(void *plugin_state,
                                                   const struct OvStorageAuthzPlugin_AuthzRequestV1 *request,
                                                   const OvStoragePlugin_List_Str *addresses,
                                                   const OvStoragePlugin_CancelTokenFFI *cancel,
                                                   OvStorageAuthzPlugin_AuthzFilterCallback on_complete,
                                                   void *user_data);

/**
 * Vtable for one authz plugin instance. Lifecycle: `configure` once,
 * then `authorize` / `filter_list_batch` per request.
 */
typedef struct OvStorageAuthzPlugin_AuthzPluginVTableV1 {
  size_t struct_size;
  OvStoragePlugin_VTableDropFn drop;
  OvStorageAuthzPlugin_AuthzConfigureFn configure;
  OvStorageAuthzPlugin_AuthzAuthorizeFn authorize;
  OvStorageAuthzPlugin_AuthzFilterFn filter_list_batch;
} OvStorageAuthzPlugin_AuthzPluginVTableV1;

/**
 * Result returned by `ovstorage_authz_plugin_init_v1`.
 */
typedef struct OvStorageAuthzPlugin_AuthzPluginInitResultV1 {
  size_t struct_size;
  uint32_t abi_version;
  void *plugin_state;
  const struct OvStorageAuthzPlugin_AuthzPluginVTableV1 *vtable;
} OvStorageAuthzPlugin_AuthzPluginInitResultV1;

#endif  /* OVSTORAGE_AUTHZ_PLUGIN_H */
