// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { ClientVersion, ServerVersion, Version } from "@plugins/versions";

interface Credentials {
  get_settings(version: ClientVersion): CredentialSettings;
  /**
   * Authenticates the client using the specified credentials.
   * Supports `nonce` that represents a random string generated by the service to let clients subscribe to
   * the authentication results.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 2
   */
  auth(
    version: ClientVersion,
    username: string,
    password: string,
    nonce?: string,
    client_id?: string
  ): Auth;

  /**
   * Register the client using the specified credentials and profile.
   * Supports `nonce` that represents a random string generated by the service to let clients subscribe to
   * the authentication results.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 3
   * @deprecated
   */
  register(
    version: ClientVersion,
    username: string,
    password: string,
    profile: Profile,
    nonce?: string,
    client_id?: string
  ): Auth;

  /**
   * Resets the current user password with the specified API token.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 2
   */
  reset(
    version: ClientVersion,
    username: string,
    new_password: string,
    token: string,
    client_id?: string
  ): Auth;
}

interface Profiles {
  get_settings(version: ClientVersion): ProfileSettings;
  get_all(version: ClientVersion, token: string): ProfileResponse[];
  get(version: ClientVersion, username: string): ProfileResponse;

  /**
   * Provide option to change users username
   * @param new_username
   * @version 2
   */
  set_info(
    version: ClientVersion,
    username: string,
    token: string,
    first_name?: string,
    last_name?: string,
    email?: string,
    new_username?: string,
  ): ProfileResponse;
  set_enabled(
    version: ClientVersion,
    username: string,
    token: string,
    enabled: boolean
  ): ProfileResponse;
  set_admin(
    version: ClientVersion,
    username: string,
    token: string,
    admin: boolean
  ): ProfileResponse;
  set_nucleus_ro(
    version: ClientVersion,
    username: string,
    token: string,
    nucleus_ro: boolean
  ): ProfileResponse;
  add(
    version: ClientVersion,
    username: string,
    token: string,
    first_name?: string,
    last_name?: string,
    email?: string
  ): ProfileResponse;
}

interface SSO {
  get_settings(version: ClientVersion): SSOSettings[];

  /**
   * Authenticates the client using the SSO parameters passed by an external authentication provider.
   * Supports `nonce` that represents a random string generated by the service to let clients subscribe to
   * the authentication results.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 2
   */
  auth(
    version: ClientVersion,
    type: string,
    params: SSOParams,
    nonce?: string,
    client_id?: string
  ): Auth;

  /**
   * Returns a redirect URL that can be used to navigate to the external authentication provider.
   * Might be needed for some authentication methods that require to sign the query parameters.
   *
   * The `state` argument allows to pass local state to be sent the authentication provider
   * and then restored back in the application when the SSO result is returned.
   * @version 1
   */
  redirect(
    version: ClientVersion,
    type: string,
    state?: string,
    nonce?: string
  ): SSORedirect;
}

interface Tokens {
  /**
   * Allows administrator to generate tokens for users.
   * Can let the user to work in a system for a limited period of time and reset his password.
   * Returns a one-time API token as an access_token value.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 2
   */
  generate(
    version: ClientVersion,
    username: string,
    admin_token: string,
    client_id?: string
  ): Auth;

  /**
   * Refreshes the authentication using a refresh token.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 1
   */
  refresh(
    version: ClientVersion,
    refresh_token: string,
    client_id?: string
  ): Auth;

  /**
   * Invalidates refresh tokens for the specified user.
   * This method is only available for administrators.
   * Optionally accepts a refresh token that needs to be invalidated.
   */
  invalidate(
    version: ClientVersion,
    username: string,
    admin_token: string,
    refresh_token?: string
  ): Auth;

  /**
   * Returns `nonce` with a random string and subscribes to its authentication results.
   * Clients can use the login form with the `nonce` query argument.
   * In this case, the login form will pass this `nonce` string back to the service to make it
   * publish authentication tokens to this subscription.
   *
   * The first response returns an object with `status` equal to `AuthStatus.Subscribed` and `nonce`
   * that should be sent to the login form.
   * The following response returns the authentication result from the login form.
   */
  subscribe(version: ClientVersion): Auth[];

  /**
   * Create a new API token.
   * `expire_at` is an ISO-8601 date describing when this token must be revoked.
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 2
   */
  create_api_token(
    version: ClientVersion,
    access_token: string,
    name: string,
    expire_at?: string,
    client_id?: string
  ): CreateApiToken;

  /**
   * Delete API token
   */
  delete_api_token(
    version: ClientVersion,
    access_token: string,
    name: string
  ): DeleteApiToken;

  /**
   * List API tokens
   */
  get_api_tokens(version: ClientVersion, access_token: string): GetApiTokens;

  /**
   * Auth using API token
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @version 1
   */
  auth_with_api_token(
    version: ClientVersion,
    api_token: string,
    client_id?: string
  ): Auth;
}

interface UserStore {
  /**
   * Returns value in the user's store by the specified key.
   * If the key does not exist, returns AuthStatus.NotFound.
   */
  get(version: ClientVersion, key: string, token: string): UserStoreResult;
  set(
    version: ClientVersion,
    key: string,
    value: string,
    token: string
  ): UserStoreResult;
  /**
   * Removes value from the user's store by the specified key.
   * If the key does not exist, returns AuthStatus.NotFound.
   */
  remove(version: ClientVersion, key: string, token: string): UserStoreResult;
}

interface DeviceFlow {
  /**
   * Starts the device flow authentication.
   * @param version
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   */
  authorize(version: ClientVersion, client_id: string): DeviceAuthorize;

  /**
   * Sends a signal that the user has entered the specified `user_code`.
   * - AuthStatus.Expired, if `access_token` has expired.
   * - AuthStatus.InvalidToken, if `access_token` is invalid.
   * - AuthStatus.NotFound, if user code is used or expired.
   * - AuthStatus.Disabled, if `access_token` is disabled.
   * - AuthStatus.OK, if results are submitted successfully.
   * @param version
   * @param access_token The access token identifying the user.
   * @param user_code The user code entered in the form.
   */
  submit(
    version: ClientVersion,
    access_token: string,
    user_code: string
  ): DeviceSubmit;

  /**
   * Returns the authentication for the specified `client_id` and `device_code`.
   *  - AuthStatus.NotFound, if the service cannot find the pair of `client_id` and `device_code`.
   *  - AuthStatus.Pending, if the client should wand and try again after `interval` returned from `Device.authorize`.
   *  - AuthStatus.Expired, if `device_code` has expired.
   *  - AuthStatus.OK, if result is ready. Includes `access_token`, `refresh_token` and `profile` in this case.
   * @param version
   * @param client_id Defines an identifier representing the client app. Can be any string like "Navigator 3.3.0".
   * @param device_code The code returned from `Device.authorize` method.
   */
  token(version: ClientVersion, client_id: string, device_code: string): Auth;
}

type Auth = {
  status: AuthStatus;
  version: Version;
  access_token?: string;
  refresh_token?: string;
  username?: string;
  profile?: Profile;
  nonce?: string;
};

type Profile = {
  first_name?: string;
  last_name?: string;
  email?: string;
  admin?: boolean;
  provider?: string;
  readonly?: boolean;
  nucleus_ro?: boolean;
  enabled?: boolean;
  activated?: boolean;
};

enum AuthStatus {
  OK = "OK",
  NotFound = "NOT_FOUND",
  Exists = "EXISTS",
  Disabled = "DISABLED",
  Denied = "DENIED",
  Expired = "EXPIRED",
  ReadOnly = "READONLY",
  UsernameRequired = "USERNAME_REQUIRED",
  NotSupported = "NOT_SUPPORTED",
  ConnectionError = "CONNECTION_ERROR",
  InternalError = "INTERNAL_ERROR",
  InvalidUsername = "INVALID_USERNAME",
  UnknownError = "UNKNOWN_ERROR",
  InvalidToken = "INVALID_TOKEN",
  /**
   * Returned when the client successfully subscribes to authentication results passing `nonce` argument to
   * `Tokens.subscribe` method.
   */
  Subscribed = "SUBSCRIBED",
  InvalidRequest = "INVALID_REQUEST",

  /**
   * Returned when the client needs to wait for some time and try the request again.
   */
  Pending = "PENDING",
}

type CredentialSettings = {
  login_url?: string;
  can_register?: boolean;

  // Defines whether the credential authentication available in the login form.
  is_ui_visible?: boolean;
  version?: ServerVersion<Credentials["get_settings"]>;
};

type ProfileResponse = {
  status: AuthStatus;
  version: Version;
  username?: string;
  profile?: Profile;
};

type ProfileSettings = {
  can_manage: boolean;
  version: ServerVersion<Profiles["get_settings"]>;
};

type SSOSettings = {
  public_name: string;
  type: string;
  redirect?: string;
  image: string;
  version: ServerVersion<SSO["get_settings"]>;
  // Specifies whether the auth flow is interactive (user-initiated).
  interactive: boolean;
};

type SSORedirect = {
  status: AuthStatus;
  redirect: string;
};

type SSOParams = {
  [key: string]: string;
};

enum AuthProvider {
  Internal = "Internal",
  NVIDIA = "NVIDIA",
  Starfleet = "Starfleet",
  GFN = "GFN",
  NGC = "NGC",
  System = "System",
  SAML = "SAML",
  OpenID = "OpenID",
}

type UserStoreResult = {
  status: AuthStatus;
  version: Version;
  value?: string;
};

type CreateApiToken = {
  status: AuthStatus;
  version: Version;
  token?: string;
};

type DeleteApiToken = {
  status: AuthStatus;
  version: Version;
};

type ApiToken = {
  name: string;
};

type GetApiTokens = {
  status: AuthStatus;
  version: Version;
  tokens?: ApiToken[];
};

type DeviceAuthorize = {
  version: Version;

  /**
   * The code to present to the user, that the user needs to enter on the web page.
   */
  user_code: string;

  /**
   * The URL the user should visit to enter the `user_code` and authenticate.
   */
  verification_uri: string;

  /**
   * The shorthand URL with the user_code added as query.
   * Should be used if automatic login is preferred.
   */
  verification_uri_complete: string;

  /**
   * The URL that can be used to force users enter credentials or use SSO.
   */
  prompt_url: string;

  /**
   * The code the device should use to poll and retrieve tokens.
   */
  device_code: string;

  /**
   * The polling interval in seconds the device should use when waiting for token results.
   */
  interval: number;

  /**
   * The time in seconds the `device_code` and `user_code` is valid for.
   */
  expires_in: number;
};

type DeviceSubmit = {
  version: Version;

  /**
   * The status identifying if the entered code is valid:
   *  - AuthStatus.OK, if `user_code` is accepted.
   *  - AuthStatus.NotFound, if `user_code` is not found or expired.
   *  - AuthStatus.InvalidToken, if specified token is invalid.
   *  - AuthStatus.Expired, if specified token has expired.
   */
  status: AuthStatus;
};
