# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import builtins
from typing import Any, AsyncIterator, Awaitable, Callable, Mapping, Sequence

__version__: str
__all__: builtins.list[str]


def init_auth_substrate(auth_dir: str | None = None) -> None: ...


class CredentialCacheDurability:
    """Mirror of the Rust `CredentialCacheDurability` enum (ticket #64).

    Pass the integer value to `Library.open(credential_cache_durability=...)`.
    """

    PERSISTENT: int
    IN_MEMORY_ONLY: int


class InteractiveAuthCapability:
    """Mirror of the Rust `InteractiveAuthCapability` enum (tickets #62 / #64).

    Pass the integer value to `Library.open(interactive_auth_capability=...)`.
    """

    BROWSER: int
    HEADLESS: int
    NONE: int


class Error(Exception):
    code: str
    next_action: str | None


class NotFoundError(Error): ...
class AlreadyExistsError(Error): ...
class PermissionDeniedError(Error): ...
class PreconditionFailedError(Error): ...
class ConflictError(Error): ...
class DirectoryNotEmptyError(Error): ...
class UnsupportedError(Error): ...
class InvalidArgumentError(Error): ...
class IncompatibleTypeError(Error): ...
class LockedError(Error): ...
class CancelledError(Error): ...
class DeadlineExceededError(Error): ...
class TransientError(Error): ...
class ResourceExhaustedError(Error): ...
class IntegrityFailureError(Error): ...
class InternalError(Error): ...
class BrokerUnavailableError(Error): ...
class BrokerRequiredError(Error): ...
class RedirectExpiredError(Error): ...
class PolicyEpochStaleError(Error): ...
class AuthorizationLeaseExpiredError(Error): ...
class CacheCorruptError(Error): ...
class StagingExpiredError(Error): ...
class CommitAmbiguousError(Error): ...
class CacheLockContentionError(Error): ...
class StateRootUnavailableError(Error): ...
class NetworkFilesystemRefusedError(Error): ...
class ObjectModifiedError(Error): ...
class NoRouteError(Error): ...
class RouteConflictError(Error): ...
class NotConfiguredError(Error): ...
class AliasChainTooLongError(Error): ...
class CredentialExpiredError(Error): ...
class CredentialUnavailableError(Error): ...
class AuthRequiredError(Error): ...
class AuthCancelledError(Error): ...
class AuthExpiredError(Error): ...
class ContentMismatchError(Error): ...
class ContentChecksumMismatchError(Error): ...
class PluginRejectedError(Error): ...


class Info:
    address: str
    kind: str
    size: int | None
    mtime_unix_nanos: int | None
    etag: str | None
    version: str | None
    system_metadata: dict[str, str]
    user_metadata: dict[str, str]


class ListPage:
    items: list[Info]
    next_page_token: str | None


class VersionPage:
    items: list[Info]
    next_page_token: str | None


class LocalDelegate:
    """Lease-backed local path returned by Library.materialize().

    The path remains valid while this object/context manager is alive.
    Copy from path before close if you need a durable caller-owned file.
    """

    path: str
    info: Info
    @property
    def closed(self) -> bool: ...
    def __fspath__(self) -> str: ...
    async def __aenter__(self) -> LocalDelegate: ...
    async def __aexit__(
        self,
        exc_type: type | None = None,
        exc: BaseException | None = None,
        tb: object | None = None,
    ) -> bool: ...
    def __enter__(self) -> LocalDelegate: ...
    def __exit__(
        self,
        exc_type: type | None = None,
        exc: BaseException | None = None,
        tb: object | None = None,
    ) -> bool: ...
    async def close(self) -> None: ...


class AccessDecision:
    allowed: bool
    denied_read: bool
    denied_write: bool
    denied_delete: bool
    denied_update_metadata: bool
    reason: str | None


class AsyncReadStream(AsyncIterator[bytes]):
    def __aiter__(self) -> AsyncReadStream: ...
    async def __anext__(self) -> bytes: ...


# ---- Connection / auth / aliases / discovery surface ----

class ConfigValue:
    @classmethod
    def string(cls, value: str) -> ConfigValue: ...
    @classmethod
    def int_(cls, value: int) -> ConfigValue: ...
    @classmethod
    def bool_(cls, value: bool) -> ConfigValue: ...
    @classmethod
    def toml(cls, toml: str) -> ConfigValue: ...
    @property
    def kind(self) -> str: ...
    @property
    def as_string(self) -> str | None: ...
    @property
    def as_int(self) -> int | None: ...
    @property
    def as_bool(self) -> bool | None: ...
    @property
    def as_toml(self) -> str | None: ...


class SecretValue:
    @classmethod
    def bytes(cls, data: builtins.bytes) -> SecretValue: ...
    @classmethod
    def file(cls, data: builtins.bytes) -> SecretValue: ...
    @classmethod
    def oauth_token(
        cls,
        token: builtins.bytes,
        refresh: builtins.bytes | None = None,
        expires_at_unix_nanos: int | None = None,
    ) -> SecretValue: ...
    @classmethod
    def mtls_cert_pair(cls, cert_pem: builtins.bytes, key_pem: builtins.bytes) -> SecretValue: ...
    @classmethod
    def system_identity(cls) -> SecretValue: ...


class SecretBundle:
    def __init__(self) -> None: ...
    def add(self, key: str, value: SecretValue) -> None: ...


class ConnectionRequest:
    def __new__(cls, backend_kind: str) -> ConnectionRequest: ...
    def add_config(self, key: str, value: ConfigValue) -> None: ...
    def add_credential(self, key: str, value: SecretValue) -> None: ...
    def set_persist(self, persist: bool) -> None: ...
    def set_display_name(self, display_name: str | None = None) -> None: ...


class Capabilities:
    @property
    def supports_if_match_write(self) -> bool: ...
    @property
    def supports_no_overwrite_write(self) -> bool: ...
    @property
    def supports_recursive_list(self) -> bool: ...
    @property
    def has_real_directories(self) -> bool: ...
    @property
    def writes_are_atomic(self) -> bool: ...
    @property
    def supports_access_check(self) -> bool: ...
    @property
    def supports_watch_directory(self) -> bool: ...
    @property
    def supports_version_listing(self) -> bool: ...
    @property
    def redirect_size_threshold(self) -> int | None: ...


class Connection:
    @property
    def id(self) -> str: ...
    @property
    def backend_kind(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def addresses(self) -> list[str]: ...
    @property
    def auth_state_kind(self) -> str: ...
    @property
    def capabilities(self) -> Capabilities: ...
    @property
    def user_metadata(self) -> dict[str, str]: ...


class AuthEvent:
    @property
    def kind(self) -> str: ...
    @property
    def url(self) -> str | None: ...
    @property
    def user_code(self) -> str | None: ...
    @property
    def verification_url(self) -> str | None: ...
    @property
    def message(self) -> str | None: ...
    @property
    def connection(self) -> Connection | None: ...
    @property
    def oauth_access_token(self) -> bytes | None: ...
    @property
    def oauth_refresh_token(self) -> bytes | None: ...
    @property
    def error_code(self) -> str | None: ...


class AsyncAuthEventStream(AsyncIterator[AuthEvent]):
    def __aiter__(self) -> AsyncAuthEventStream: ...
    async def __anext__(self) -> AuthEvent: ...


class AliasRequest:
    def __new__(cls, from_: str, to: str) -> AliasRequest: ...
    def set_visibility(self, visibility: str) -> None: ...
    def set_persist(self, persist: bool) -> None: ...
    def set_display_name(self, display_name: str | None = None) -> None: ...
    def add_user_metadata(self, key: str, value: str) -> None: ...


class Alias:
    @property
    def id(self) -> str: ...
    @property
    def from_(self) -> str: ...
    @property
    def to(self) -> str: ...
    @property
    def visibility(self) -> str: ...
    @property
    def state_kind(self) -> str: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def user_metadata(self) -> dict[str, str]: ...


class AsyncAddressRootSnapshotStream(AsyncIterator[list[AddressRoot]]):
    def __aiter__(self) -> AsyncAddressRootSnapshotStream: ...
    async def __anext__(self) -> list[AddressRoot]: ...


class AddressVisibilityOverride:
    @property
    def address(self) -> str: ...
    @property
    def visibility(self) -> str: ...
    @property
    def persisted(self) -> bool: ...


class AddressRoot:
    @property
    def address(self) -> str: ...
    @property
    def backend_kind(self) -> str: ...
    @property
    def display_name(self) -> str | None: ...
    @property
    def connection_id(self) -> str | None: ...
    @property
    def visibility(self) -> str: ...
    @property
    def capabilities(self) -> Capabilities: ...
    @property
    def user_metadata(self) -> dict[str, str]: ...


class BackendKindDescriptor:
    @property
    def kind(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def supports_runtime_add(self) -> bool: ...


class Library:
    def __init__(self) -> None: ...
    @staticmethod
    def open(
        interactive_auth_capability: int | None = None,
        credential_cache_durability: int | None = None,
        credential_callback: Callable[[str, str], Awaitable[Mapping[str, Any]] | Mapping[str, Any]] | None = None,
        credential_callback_name: str | None = None,
        allow_test_plugins: bool = False,
    ) -> Library: ...
    async def load_plugin(self, path: str) -> None: ...
    async def load_plugins_from_dir(self, dir: str | None = None) -> None: ...
    async def load_config(self, path: str | None = None) -> list[Connection]: ...
    async def set_credential(
        self,
        backend_id: str,
        principal_id: str,
        credential: Mapping[str, Any],
    ) -> None: ...
    async def stat(self, address: str, full_metadata: bool = False) -> Info: ...
    async def read_bytes(
        self, address: str, max_bytes: int | None = None
    ) -> tuple[bytes, Info]: ...
    async def read_stream(
        self, address: str, max_bytes: int | None = None
    ) -> tuple[AsyncReadStream, Info]: ...
    async def materialize(self, address: str) -> LocalDelegate: ...
    async def write(
        self, address: str, data: bytes | bytearray | memoryview
    ) -> Info: ...
    async def delete(self, address: str) -> None: ...
    async def list(
        self,
        prefix: str,
        recursive: bool = False,
        max_results: int | None = None,
        page_token: str | None = None,
        full_metadata: bool = False,
    ) -> ListPage: ...
    async def list_versions(
        self,
        address: str,
        max_results: int | None = None,
        page_token: str | None = None,
    ) -> VersionPage: ...
    async def get_latest_version(self, address: str) -> Info: ...
    async def copy(self, src: str, dest: str) -> Info: ...
    async def rename(self, src: str, dest: str) -> None: ...
    async def create_directory(self, address: str) -> Info: ...
    async def delete_directory(self, address: str) -> None: ...
    async def update_metadata(
        self,
        address: str,
        set: Mapping[str, str] | None = None,
        remove: Sequence[str] | None = None,
        message: str | None = None,
    ) -> Info: ...
    async def check_access(
        self,
        address: str,
        read: bool = False,
        write: bool = False,
        delete: bool = False,
        update_metadata: bool = False,
    ) -> AccessDecision: ...
    # Connection / auth / aliases / discovery
    async def add_connection(self, request: ConnectionRequest) -> Connection: ...
    async def remove_connection(self, connection_id: str) -> None: ...
    async def list_connections(self) -> builtins.list[Connection]: ...
    async def update_connection_credentials(
        self, connection_id: str, credentials: SecretBundle
    ) -> Connection: ...
    async def authenticate_connection(
        self, connection_id: str
    ) -> AsyncAuthEventStream: ...
    async def add_alias(self, request: AliasRequest) -> Alias: ...
    async def remove_alias(self, alias_id: str) -> None: ...
    async def list_aliases(self) -> builtins.list[Alias]: ...
    async def watch_address_roots(self) -> AsyncAddressRootSnapshotStream: ...
    async def set_address_visibility(
        self, address: str, visibility: str, persist: bool
    ) -> AddressVisibilityOverride: ...
    async def list_address_visibility_overrides(
        self,
    ) -> builtins.list[AddressVisibilityOverride]: ...
    async def list_address_roots(self) -> builtins.list[AddressRoot]: ...
    async def list_backend_kinds(self) -> builtins.list[BackendKindDescriptor]: ...
    async def capabilities_for(self, prefix: str) -> Capabilities: ...
