// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

syntax = "proto3";

package nvidia.omniverse.storage.capabilities.v1beta;

option go_package = "pb.api.nvidia.com/omniverse/storage/capabilities/v1beta;storage";
option java_multiple_files = true;
option java_outer_classname = "CapabilitiesProto";
option java_package = "com.nvidia.omniverse.storage.capabilities.v1beta";

// The CapabilitiesService is used to reflect on which services are implemented by this server.
// Each service in turn exposes another service-specific capabilities query,
// to read data from remote storage.
service CapabilitiesService {
  // Return the list of service API implemented by this service
  rpc ListServices(ListServicesRequest) returns (ListServicesResponse);
  // Return a list of top level resource addresses that is suited for browsing this storage service by the user.
  rpc ListTopLevelAddresses(ListTopLevelAddressesRequest) returns (ListTopLevelAddressesResponse);
}

// Empty message to call the ListServicesRequest.
message ListServicesRequest {}

// Response of the ListServices call
message ListServicesResponse {
  // List of services with details implemented by this Storage API server
  repeated ServiceEntry services = 1;
}

// One Service is described via name and a list of versions supported by this server
message ServiceEntry {
  // The name of the service, e.g. fileobject
  // (-- api-linter: core::0122::name-suffix=disabled
  //     aip.dev/not-precedent: "service_name" is better than "service" --)
  string service_name = 1;
  // List of versions supported for this service, e.g. v1, v2alpha1, v2beta
  repeated string service_versions = 2;
}

// Empty message to call the ListTopLevelAddresses method
message ListTopLevelAddressesRequest {}

// The List of top level resource addresses served by this service instance.
// This is a convenience function to allow UI clients to explore the data exposed by this storage service, and does
// not need to be complete. I.e. it could list a number of buckets configured, but still allow to access arbitrary
// public buckets without needing to enumerate all of them.
message ListTopLevelAddressesResponse {
  // A list of top level resource addresses
  repeated TopLevelAddressEntry items = 1;
}

// One TopLevelAddress
message TopLevelAddressEntry {
  // The root of a namespace. All resource addresses that start with this prefix are considered to be within this namespace
  string top_level_address = 1;
}
