# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ovstorage-plugin-file"
version = "0.1.0"
edition = "2024"
description = "file: backend for ovstorage."
license = "Apache-2.0"
build = "build.rs"

[dependencies]
ovstorage-plugin = { version = "0.1.0", path = "../ovstorage-plugin" }
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "rt", "sync"] }
tokio-util = { workspace = true, features = ["io"] }
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
] }

[dev-dependencies]
ovstorage = { version = "0.1.0", path = "../ovstorage" }
ovstorage-cache = { version = "0.1.0", path = "../ovstorage-cache" }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
