/* SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * ovstorage library C ABI.
 *
 * Generated by cbindgen from crates/ovstorage-capi/src/{lib.rs,ops.rs}.
 * Do not edit by hand: edit the Rust source and rerun `cargo build` on
 * the crate. The build script regenerates this file in-place; the file
 * is checked in for code review and IDE consumption.
 */


#ifndef OVSTORAGE_H
#define OVSTORAGE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum {
  OvStorage_Status_Ok = 0,
  OvStorage_Status_NotFound = 1,
  OvStorage_Status_AlreadyExists = 2,
  OvStorage_Status_PermissionDenied = 3,
  OvStorage_Status_PreconditionFailed = 4,
  OvStorage_Status_Conflict = 5,
  OvStorage_Status_DirectoryNotEmpty = 6,
  OvStorage_Status_Unsupported = 7,
  OvStorage_Status_InvalidArgument = 8,
  OvStorage_Status_ObjectModified = 9,
  OvStorage_Status_NoRoute = 10,
  OvStorage_Status_Transient = 11,
  OvStorage_Status_Cancelled = 12,
  OvStorage_Status_Internal = 255,
} OvStorage_Status;

typedef enum {
  OvStorage_ObjectKind_File = 0,
  OvStorage_ObjectKind_Directory = 1,
  OvStorage_ObjectKind_DirectoryMarker = 2,
  OvStorage_ObjectKind_DirectoryInferred = 3,
} OvStorage_ObjectKind;

typedef enum {
  OvStorage_AddressVisibility_Visible = 0,
  OvStorage_AddressVisibility_Hidden = 1,
  OvStorage_AddressVisibility_Suppressed = 2,
} OvStorage_AddressVisibility;

typedef enum {
  OvStorage_AliasSourceKind_Static = 0,
  OvStorage_AliasSourceKind_Runtime = 1,
  OvStorage_AliasSourceKind_BrokerDelivered = 2,
} OvStorage_AliasSourceKind;

typedef enum {
  OvStorage_ConfigLayer_Programmatic = 0,
  OvStorage_ConfigLayer_Env = 1,
  OvStorage_ConfigLayer_Project = 2,
  OvStorage_ConfigLayer_User = 3,
  OvStorage_ConfigLayer_Machine = 4,
} OvStorage_ConfigLayer;

typedef enum {
  OvStorage_AliasStateKind_Live = 0,
  OvStorage_AliasStateKind_Dangling = 1,
  OvStorage_AliasStateKind_ChainTooLong = 2,
} OvStorage_AliasStateKind;

typedef enum {
  OvStorage_AuthEventKind_OpenBrowser = 0,
  OvStorage_AuthEventKind_DeviceCode = 1,
  OvStorage_AuthEventKind_Progress = 2,
  OvStorage_AuthEventKind_Succeeded = 3,
  OvStorage_AuthEventKind_Failed = 4,
  OvStorage_AuthEventKind_Cancelled = 5,
} OvStorage_AuthEventKind;

typedef enum {
  OvStorage_ConfigValueKind_String = 0,
  OvStorage_ConfigValueKind_Int = 1,
  OvStorage_ConfigValueKind_Bool = 2,
  /**
   * Reserialized TOML payload (a nested table or array of tables).
   * The plugin reading the value parses the string with its own
   * TOML deserializer.
   */
  OvStorage_ConfigValueKind_Toml = 3,
} OvStorage_ConfigValueKind;

typedef enum {
  OvStorage_VersionListOrder_Newest = 0,
  OvStorage_VersionListOrder_Oldest = 1,
  OvStorage_VersionListOrder_Unordered = 2,
} OvStorage_VersionListOrder;

typedef enum {
  OvStorage_ConnectionSourceKind_Static = 0,
  OvStorage_ConnectionSourceKind_Runtime = 1,
  OvStorage_ConnectionSourceKind_BrokerDelivered = 2,
} OvStorage_ConnectionSourceKind;

typedef enum {
  OvStorage_ConnectionAuthStateKind_Authenticated = 0,
  OvStorage_ConnectionAuthStateKind_AwaitingAuth = 1,
  OvStorage_ConnectionAuthStateKind_AuthFailed = 2,
  OvStorage_ConnectionAuthStateKind_Anonymous = 3,
} OvStorage_ConnectionAuthStateKind;

typedef enum {
  OvStorage_RouteSourceKind_Static = 0,
  OvStorage_RouteSourceKind_ConnectionContributed = 1,
  OvStorage_RouteSourceKind_BrokerDelivered = 2,
  OvStorage_RouteSourceKind_Alias = 3,
} OvStorage_RouteSourceKind;

typedef struct OvStorage_AddressRoot OvStorage_AddressRoot;

typedef struct OvStorage_AddressRootList OvStorage_AddressRootList;

typedef struct OvStorage_AddressVisibilityOverride OvStorage_AddressVisibilityOverride;

typedef struct OvStorage_AddressVisibilityOverrideList OvStorage_AddressVisibilityOverrideList;

typedef struct OvStorage_Alias OvStorage_Alias;

typedef struct OvStorage_AliasList OvStorage_AliasList;

/**
 * Opaque alias-request builder. Built with
 * `ovstorage_alias_request_create(from, to)` and per-field setters;
 * consumed by `ovstorage_library_add_alias`. Ownership matches
 * `ConnectionRequest`: the caller's `*mut` is invalidated on success;
 * on a prologue error the caller still owns it (and must free with
 * `ovstorage_alias_request_destroy`).
 */
typedef struct OvStorage_AliasRequest OvStorage_AliasRequest;

/**
 * Opaque single-event handle. Variant is read via
 * `ovstorage_auth_event_kind`; accessors for non-matching variants
 * return NULL/0.
 */
typedef struct OvStorage_AuthEvent OvStorage_AuthEvent;

typedef struct OvStorage_BackendKindDescriptor OvStorage_BackendKindDescriptor;

typedef struct OvStorage_BackendKindDescriptorList OvStorage_BackendKindDescriptorList;

typedef struct OvStorage_CancelToken OvStorage_CancelToken;

/**
 * Opaque config-value handle. Built via `ovstorage_config_value_create_*`;
 * freed via `ovstorage_config_value_destroy` (or consumed by
 * `ovstorage_connection_request_add_config`).
 */
typedef struct OvStorage_ConfigValue OvStorage_ConfigValue;

/**
 * Opaque connection handle. Owned strings are pre-baked into
 * CStrings so per-field accessors return borrowed pointers valid
 * for the lifetime of the handle.
 *
 * Variant payloads for the `Authenticated` and `AwaitingAuth`
 * auth-state variants are not yet exposed; only `Anonymous` and
 * `AuthFailed` are reachable today.
 */
typedef struct OvStorage_Connection OvStorage_Connection;

/**
 * Opaque list of `Connection` handles returned by
 * `ovstorage_library_list_connections`. Items are borrowed from the
 * list — do NOT call `ovstorage_connection_destroy` on items;
 * destroying the list frees them.
 */
typedef struct OvStorage_ConnectionList OvStorage_ConnectionList;

/**
 * Opaque connection-request builder. Built with
 * `ovstorage_connection_request_create` + per-field setters;
 * consumed by `ovstorage_library_add_connection`. On success the
 * caller's `*mut` is invalidated; on a prologue error the caller
 * still owns it and must free with
 * `ovstorage_connection_request_destroy`.
 */
typedef struct OvStorage_ConnectionRequest OvStorage_ConnectionRequest;

typedef struct OvStorage_Info OvStorage_Info;

typedef struct OvStorage_Library OvStorage_Library;

typedef struct OvStorage_List OvStorage_List;

typedef struct OvStorage_LocalDelegate OvStorage_LocalDelegate;

/**
 * Opaque secret-bundle handle for `OvResolvedCredentialV1`. Built
 * with `ovstorage_resolved_credential_bundle_create`, populated via
 * `_add_field`, consumed by the host on success.
 */
typedef struct OvStorage_OvResolvedCredentialBundle OvStorage_OvResolvedCredentialBundle;

/**
 * Opaque secret-bundle handle used by
 * `ovstorage_library_update_connection_credentials` to refresh an
 * existing connection's credentials.
 *
 * On success the bundle is consumed; on a prologue error the caller
 * still owns it and must free with `ovstorage_secret_bundle_destroy`.
 */
typedef struct OvStorage_SecretBundle OvStorage_SecretBundle;

/**
 * Opaque secret-value handle. Write-only — secrets never flow back
 * out across the C ABI.
 *
 * All `_create_*` constructors copy the input bytes into a host-owned
 * zero-on-drop buffer; the caller may free input pointers as soon as
 * the constructor returns.
 */
typedef struct OvStorage_SecretValue OvStorage_SecretValue;

typedef struct OvStorage_UpdateMetadataOptions OvStorage_UpdateMetadataOptions;

typedef struct OvStorage_VersionList OvStorage_VersionList;

typedef struct {
  OvStorage_Status code;
  char *message;
} OvStorage_Error;

/**
 * Reserved trailing padding on every public V1 options struct.
 *
 * 8 pointer-sized slots reserved for future fields. Callers MUST
 * zero-initialize every slot. New fields are added before
 * `_reserved`; existing fields are never reordered.
 */
typedef const void *OvStorage_ReservedOptionsPadding[8];

/**
 * Resolved-credential payload passed into the host (via
 * `ovstorage_library_set_credential` or
 * `OvCredentialCallbackCompletion`).
 *
 * The bundle is built via
 * `ovstorage_resolved_credential_bundle_create` +
 * `ovstorage_resolved_credential_bundle_add_field`. `source_name`
 * is borrowed for the duration of the call only — the host copies
 * it internally.
 */
typedef struct {
  size_t struct_size;
  /**
   * Opaque secret-bundle handle; consumed by the host on success.
   */
  OvStorage_OvResolvedCredentialBundle *bundle;
  bool has_expires_at;
  uint64_t expires_at_unix_nanos;
  /**
   * Borrowed C-string. Required (non-null). Must be valid UTF-8.
   */
  const char *source_name;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_OvResolvedCredentialV1;

/**
 * One-shot completion callback fired by the host's `resolve`
 * implementation when the async credential-fetch is done.
 *
 * `status == Status::Ok` and `credential != NULL` on success; any
 * other status with `credential == NULL` on failure. Fire EXACTLY
 * ONCE — the host's internal sender is consumed on the call.
 */
typedef void (*OvStorage_OvCredentialCallbackCompletion)(void *completion_userdata,
                                                         OvStorage_Status status,
                                                         const OvStorage_OvResolvedCredentialV1 *credential);

/**
 * `resolve` may be NULL when `has_credential_callback` is `false` in
 * `LibraryInitOptionsV1` (zero-initialized form). When
 * `has_credential_callback` is `true`, `resolve` MUST be non-NULL.
 * `free_userdata` is always optional (NULL = no cleanup).
 */
typedef struct {
  void (*resolve)(void *userdata,
                  const char *backend_id,
                  const char *principal_id,
                  OvStorage_OvCredentialCallbackCompletion completion,
                  void *completion_userdata);
  void (*free_userdata)(void*);
  void *userdata;
} OvStorage_OvCredentialCallback;

typedef struct {
  size_t struct_size;
  /**
   * Number of worker threads for the library's async runtime.
   * `0` selects the default (2). Pick based on expected request
   * fan-out.
   */
  uint32_t runtime_threads;
  /**
   * Host-declared interactive-auth capability.
   * `-1`=unspecified (use smart default + env-var precedence),
   * `0`=Browser, `1`=Headless, `2`=None.
   */
  int32_t interactive_auth_capability;
  /**
   * Credential cache durability. Values match
   * [`OvCredentialCacheDurability`]: `0`=Persistent (default),
   * `1`=InMemoryOnly. Older callers (smaller `struct_size`) get
   * the Persistent default automatically.
   */
  int32_t credential_cache_durability;
  /**
   * When `true`, registers `credential_callback` as an external
   * credential provider; `credential_callback_name` is then
   * required (used in trace span attributes).
   */
  bool has_credential_callback;
  OvStorage_OvCredentialCallback credential_callback;
  /**
   * Borrowed C-string. Required when `has_credential_callback`
   * is `true`; ignored otherwise.
   */
  const char *credential_callback_name;
  /**
   * Allow loading cdylibs whose manifest declares `test_only=true`.
   * Production callers must leave this `false`.
   */
  bool allow_test_plugins;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_LibraryInitOptionsV1;

typedef struct {
  size_t struct_size;
  /**
   * Borrowed C-string. `NULL` resolves to `$OVSTORAGE_AUTH_DIR` or
   * a per-process temp dir. Calling
   * [`ovstorage_init_auth_substrate`] twice with the same resolved
   * path is a no-op; calling it with a different path returns
   * [`Status::Unsupported`].
   */
  const char *auth_dir;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_InitAuthSubstrateOptionsV1;

typedef struct {
  bool read;
  bool write;
  bool delete_;
  bool update_metadata;
} OvStorage_AccessOps;

typedef struct {
  bool allowed;
  OvStorage_AccessOps denied_ops;
  char *reason;
} OvStorage_AccessDecision;

typedef struct {
  const uint8_t *data;
  size_t len;
  void *free_ctx;
} OvStorage_Bytes;

typedef struct {
  bool created;
  bool modified;
  bool deleted;
  bool metadata_changed;
} OvStorage_ChangeKindSet;

/**
 * Flat capabilities struct. Caller stack-allocates and sets
 * `struct_size = sizeof(OvStorage_CapabilitiesV1)` before passing a
 * `*mut` to a getter. The host writes only fields up to the caller's
 * `struct_size`, so older callers compiled against a smaller v1
 * remain ABI-compatible.
 */
typedef struct {
  size_t struct_size;
  bool supports_if_match_write;
  bool supports_no_overwrite_write;
  bool supports_native_metadata_patch;
  bool supports_metadata_rewrite_emulation;
  bool writes_are_atomic;
  bool supports_server_side_copy;
  bool supports_server_side_rename;
  bool supports_atomic_rename;
  bool has_real_directories;
  bool supports_list;
  bool wants_list_backed_stat;
  bool supports_recursive_list;
  bool populates_subdirectory_metadata;
  bool supports_version_listing;
  bool has_version_list_order;
  OvStorage_VersionListOrder version_list_order;
  bool populates_effective_permissions_on_stat;
  bool supports_access_check;
  bool supports_watch_directory;
  OvStorage_ChangeKindSet watch_directory_kinds;
  bool watch_directory_resumable;
  bool has_watch_directory_max_lag;
  uint64_t watch_directory_max_lag_nanos;
  bool has_redirect_size_threshold;
  uint64_t redirect_size_threshold;
} OvStorage_CapabilitiesV1;

typedef void (*OvStorage_StatusCallback)(OvStorage_Status status,
                                         const OvStorage_Error *error,
                                         void *user_data);

typedef struct {
  size_t struct_size;
  bool full_metadata;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_StatOptionsV1;

typedef void (*OvStorage_InfoCallback)(OvStorage_Status status,
                                       OvStorage_Info *info,
                                       const OvStorage_Error *error,
                                       void *user_data);

typedef struct {
  size_t struct_size;
  bool has_range;
  uint64_t range_start;
  bool has_range_end;
  uint64_t range_end_inclusive;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_ReadOptionsV1;

typedef void (*OvStorage_ReadBytesCallback)(OvStorage_Status status,
                                            OvStorage_Bytes bytes,
                                            OvStorage_Info *info,
                                            const OvStorage_Error *error,
                                            void *user_data);

typedef void (*OvStorage_ReadStreamCallback)(OvStorage_Bytes chunk,
                                             const OvStorage_Error *error,
                                             bool done,
                                             void *user_data);

typedef void (*OvStorage_ReadLocalFileCallback)(OvStorage_Status status,
                                                OvStorage_LocalDelegate *delegate,
                                                const OvStorage_Error *error,
                                                void *user_data);

typedef struct {
  size_t struct_size;
  bool no_overwrite;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_WriteOptionsV1;

typedef struct {
  size_t struct_size;
  bool recursive;
  bool has_max_results;
  uint32_t max_results;
  const char *page_token;
  bool full_metadata;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_ListOptionsV1;

typedef void (*OvStorage_ListCallback)(OvStorage_Status status,
                                       OvStorage_List *list,
                                       const OvStorage_Error *error,
                                       void *user_data);

typedef struct {
  size_t struct_size;
  bool has_max_results;
  uint32_t max_results;
  const char *page_token;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_ListVersionsOptionsV1;

typedef void (*OvStorage_ListVersionsCallback)(OvStorage_Status status,
                                               OvStorage_VersionList *list,
                                               const OvStorage_Error *error,
                                               void *user_data);

typedef struct {
  size_t struct_size;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_CreateDirectoryOptionsV1;

typedef struct {
  size_t struct_size;
  OvStorage_ReservedOptionsPadding _reserved;
} OvStorage_DeleteDirectoryOptionsV1;

typedef void (*OvStorage_CheckAccessCallback)(OvStorage_Status status,
                                              OvStorage_AccessDecision decision,
                                              const OvStorage_Error *error,
                                              void *user_data);

typedef void (*OvStorage_ConnectionCallback)(OvStorage_Status status,
                                             OvStorage_Connection *connection,
                                             const OvStorage_Error *error,
                                             void *user_data);

typedef void (*OvStorage_ConnectionListCallback)(OvStorage_Status status,
                                                 OvStorage_ConnectionList *list,
                                                 const OvStorage_Error *error,
                                                 void *user_data);

/**
 * Multi-fire callback for `ovstorage_library_authenticate_connection`.
 *
 * Per-event fire: `event != NULL`, `error == NULL`, `done == false`;
 * the caller owns `event` and must free it with
 * `ovstorage_auth_event_destroy`.
 * Final fire on success: `event == NULL`, `error == NULL`, `done == true`.
 * Final fire on terminal error: `event == NULL`, `error != NULL`,
 * `done == true`; the error message is freed by the host after the
 * callback returns.
 */
typedef void (*OvStorage_AuthEventCallback)(OvStorage_AuthEvent *event,
                                            const OvStorage_Error *error,
                                            bool done,
                                            void *user_data);

typedef void (*OvStorage_AliasCallback)(OvStorage_Status status,
                                        OvStorage_Alias *alias,
                                        const OvStorage_Error *error,
                                        void *user_data);

typedef void (*OvStorage_AliasListCallback)(OvStorage_Status status,
                                            OvStorage_AliasList *list,
                                            const OvStorage_Error *error,
                                            void *user_data);

/**
 * Multi-fire callback for `ovstorage_library_watch_address_roots`.
 * The caller owns each `list` snapshot and must free it with
 * `ovstorage_address_root_list_destroy`.
 */
typedef void (*OvStorage_AddressRootWatchCallback)(OvStorage_AddressRootList *list,
                                                   const OvStorage_Error *error,
                                                   bool done,
                                                   void *user_data);

typedef void (*OvStorage_AddressVisibilityOverrideCallback)(OvStorage_Status status,
                                                            OvStorage_AddressVisibilityOverride *result,
                                                            const OvStorage_Error *error,
                                                            void *user_data);

typedef void (*OvStorage_AddressVisibilityOverrideListCallback)(OvStorage_Status status,
                                                                OvStorage_AddressVisibilityOverrideList *list,
                                                                const OvStorage_Error *error,
                                                                void *user_data);

typedef void (*OvStorage_AddressRootListCallback)(OvStorage_Status status,
                                                  OvStorage_AddressRootList *list,
                                                  const OvStorage_Error *error,
                                                  void *user_data);

typedef void (*OvStorage_BackendKindDescriptorListCallback)(OvStorage_Status status,
                                                            OvStorage_BackendKindDescriptorList *list,
                                                            const OvStorage_Error *error,
                                                            void *user_data);

/**
 * Callback for `ovstorage_library_capabilities_for`. The `caps`
 * pointer is borrowed for the duration of the callback only — copy
 * the struct if you need to retain it.
 */
typedef void (*OvStorage_CapabilitiesCallback)(OvStorage_Status status,
                                               const OvStorage_CapabilitiesV1 *caps,
                                               const OvStorage_Error *error,
                                               void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void ovstorage_error_clear(OvStorage_Error *error);

const char *ovstorage_error_message(const OvStorage_Error *error);

/**
 * Initialize a library handle. Builds a dedicated async runtime sized by
 * `options.runtime_threads` and returns a handle the caller must free with
 * `ovstorage_library_shutdown`. No plugins are loaded and no routes bound;
 * follow with `ovstorage_library_load_plugins_from_dir` (and optionally
 * `ovstorage_library_load_config`) before calling object operations.
 */
OvStorage_Status ovstorage_library_init(const OvStorage_LibraryInitOptionsV1 *options,
                                        OvStorage_Library **out_library,
                                        OvStorage_Error *out_error);

/**
 * Explicitly initialize the process-global auth substrate.
 *
 * The plugin SPI's host callbacks are set-once-per-process (see the
 * loader comment in `ovstorage::loader::register_host_substrate`), so
 * the `(SecretStore, AuthRefreshLock)` pair is shared across every
 * [`ovstorage_library_init`] call in one process. This function lets
 * callers pin a non-default `auth_dir` before any `Library` is built.
 *
 * `options = NULL` uses the default `auth_dir` (resolved from
 * `$OVSTORAGE_AUTH_DIR` or a per-process temp dir). Calling this
 * twice with the same resolved path is a no-op; calling it with a
 * different path returns [`Status::Unsupported`]. Calling
 * [`ovstorage_library_init`] before this function auto-initializes
 * the substrate with the default `auth_dir`.
 */
OvStorage_Status ovstorage_init_auth_substrate(const OvStorage_InitAuthSubstrateOptionsV1 *options,
                                               OvStorage_Error *out_error);

/**
 * Shut down a library and join its runtime workers. Must NOT be
 * called from within an `on_complete` callback — dropping the
 * runtime from a worker thread aborts the process.
 */
void ovstorage_library_shutdown(OvStorage_Library *library);

OvStorage_CancelToken *ovstorage_cancel_token_create(void);

void ovstorage_cancel_token_destroy(OvStorage_CancelToken *token);

void ovstorage_cancel_token_cancel(const OvStorage_CancelToken *token);

bool ovstorage_cancel_token_is_canceled(const OvStorage_CancelToken *token);

OvStorage_UpdateMetadataOptions *ovstorage_update_metadata_options_create(void);

void ovstorage_update_metadata_options_destroy(OvStorage_UpdateMetadataOptions *options);

OvStorage_Status ovstorage_update_metadata_options_set(OvStorage_UpdateMetadataOptions *options,
                                                       const char *key,
                                                       const char *value,
                                                       OvStorage_Error *out_error);

OvStorage_Status ovstorage_update_metadata_options_remove(OvStorage_UpdateMetadataOptions *options,
                                                          const char *key,
                                                          OvStorage_Error *out_error);

void ovstorage_access_decision_clear(OvStorage_AccessDecision *decision);

void ovstorage_bytes_destroy(OvStorage_Bytes *bytes);

void ovstorage_info_destroy(OvStorage_Info *info);

const char *ovstorage_info_address(const OvStorage_Info *info);

OvStorage_ObjectKind ovstorage_info_kind(const OvStorage_Info *info);

bool ovstorage_info_has_size(const OvStorage_Info *info);

uint64_t ovstorage_info_size(const OvStorage_Info *info);

bool ovstorage_info_has_mtime_unix_nanos(const OvStorage_Info *info);

uint64_t ovstorage_info_mtime_unix_nanos(const OvStorage_Info *info);

const char *ovstorage_info_etag(const OvStorage_Info *info);

const char *ovstorage_info_version(const OvStorage_Info *info);

size_t ovstorage_info_user_metadata_len(const OvStorage_Info *info);

const char *ovstorage_info_user_metadata_key(const OvStorage_Info *info, size_t index);

const char *ovstorage_info_user_metadata_value(const OvStorage_Info *info, size_t index);

size_t ovstorage_info_system_metadata_len(const OvStorage_Info *info);

const char *ovstorage_info_system_metadata_key(const OvStorage_Info *info, size_t index);

const char *ovstorage_info_system_metadata_value(const OvStorage_Info *info, size_t index);

void ovstorage_local_delegate_destroy(OvStorage_LocalDelegate *delegate);

const char *ovstorage_local_delegate_path(const OvStorage_LocalDelegate *delegate);

const OvStorage_Info *ovstorage_local_delegate_info(const OvStorage_LocalDelegate *delegate);

void ovstorage_list_destroy(OvStorage_List *list);

size_t ovstorage_list_len(const OvStorage_List *list);

const char *ovstorage_list_next_page_token(const OvStorage_List *list);

const char *ovstorage_list_item_address(const OvStorage_List *list, size_t index);

OvStorage_Info *ovstorage_list_item_info(const OvStorage_List *list, size_t index);

void ovstorage_version_list_destroy(OvStorage_VersionList *list);

size_t ovstorage_version_list_len(const OvStorage_VersionList *list);

const char *ovstorage_version_list_next_page_token(const OvStorage_VersionList *list);

const char *ovstorage_version_list_item_address(const OvStorage_VersionList *list, size_t index);

OvStorage_Info *ovstorage_version_list_item_info(const OvStorage_VersionList *list, size_t index);

OvStorage_AliasRequest *ovstorage_alias_request_create(const char *from, const char *to);

void ovstorage_alias_request_destroy(OvStorage_AliasRequest *request);

void ovstorage_alias_request_set_visibility(OvStorage_AliasRequest *request,
                                            OvStorage_AddressVisibility visibility);

void ovstorage_alias_request_set_persist(OvStorage_AliasRequest *request, bool persist);

/**
 * Set the request's display name. Pass `NULL` to clear.
 */
void ovstorage_alias_request_set_display_name(OvStorage_AliasRequest *request,
                                              const char *display_name);

/**
 * Add a user-metadata key/value pair to the request. Returns `true`
 * on success, `false` on null arg / non-UTF-8 / consumed-handle.
 */
bool ovstorage_alias_request_add_user_metadata(OvStorage_AliasRequest *request,
                                               const char *key,
                                               const char *value);

void ovstorage_alias_destroy(OvStorage_Alias *alias);

const char *ovstorage_alias_id(const OvStorage_Alias *alias);

const char *ovstorage_alias_from(const OvStorage_Alias *alias);

const char *ovstorage_alias_to(const OvStorage_Alias *alias);

OvStorage_AddressVisibility ovstorage_alias_visibility(const OvStorage_Alias *alias);

const char *ovstorage_alias_display_name(const OvStorage_Alias *alias);

size_t ovstorage_alias_user_metadata_count(const OvStorage_Alias *alias);

const char *ovstorage_alias_user_metadata_key(const OvStorage_Alias *alias, size_t index);

const char *ovstorage_alias_user_metadata_value(const OvStorage_Alias *alias, size_t index);

OvStorage_AliasSourceKind ovstorage_alias_source_kind(const OvStorage_Alias *alias);

OvStorage_ConfigLayer ovstorage_alias_source_static_layer(const OvStorage_Alias *alias);

bool ovstorage_alias_source_runtime_persisted(const OvStorage_Alias *alias);

const char *ovstorage_alias_source_broker_principal(const OvStorage_Alias *alias);

OvStorage_AliasStateKind ovstorage_alias_state_kind(const OvStorage_Alias *alias);

const char *ovstorage_alias_state_chain_too_long_reason(const OvStorage_Alias *alias);

void ovstorage_alias_list_destroy(OvStorage_AliasList *list);

size_t ovstorage_alias_list_len(const OvStorage_AliasList *list);

const OvStorage_Alias *ovstorage_alias_list_item_at(const OvStorage_AliasList *list, size_t index);

void ovstorage_auth_event_destroy(OvStorage_AuthEvent *event);

OvStorage_AuthEventKind ovstorage_auth_event_kind(const OvStorage_AuthEvent *event);

const char *ovstorage_auth_event_open_browser_url(const OvStorage_AuthEvent *event);

uint64_t ovstorage_auth_event_open_browser_expires_at_unix_nanos(const OvStorage_AuthEvent *event);

const char *ovstorage_auth_event_device_code_user_code(const OvStorage_AuthEvent *event);

const char *ovstorage_auth_event_device_code_verification_url(const OvStorage_AuthEvent *event);

uint64_t ovstorage_auth_event_device_code_expires_at_unix_nanos(const OvStorage_AuthEvent *event);

uint64_t ovstorage_auth_event_device_code_interval_nanos(const OvStorage_AuthEvent *event);

const char *ovstorage_auth_event_progress_message(const OvStorage_AuthEvent *event);

/**
 * Returns a borrowed `*const Connection` valid until the AuthEvent
 * is destroyed. Returns null if the variant is not Succeeded.
 */
const OvStorage_Connection *ovstorage_auth_event_succeeded_connection(const OvStorage_AuthEvent *event);

OvStorage_Status ovstorage_auth_event_failed_error_code(const OvStorage_AuthEvent *event);

const char *ovstorage_auth_event_failed_error_message(const OvStorage_AuthEvent *event);

OvStorage_ConfigValue *ovstorage_config_value_create_string(const char *value);

OvStorage_ConfigValue *ovstorage_config_value_create_int(int64_t value);

OvStorage_ConfigValue *ovstorage_config_value_create_bool(bool value);

/**
 * Build a Toml-variant `ConfigValue` from a TOML-formatted string.
 * Used to carry nested tables / arrays of tables across the ABI.
 */
OvStorage_ConfigValue *ovstorage_config_value_create_toml(const char *toml);

void ovstorage_config_value_destroy(OvStorage_ConfigValue *value);

OvStorage_ConfigValueKind ovstorage_config_value_kind(const OvStorage_ConfigValue *value);

/**
 * Returns a borrowed `*const c_char` that is valid until the handle
 * is destroyed. Returns null if the variant is not String or the
 * handle is null.
 */
const char *ovstorage_config_value_as_string(const OvStorage_ConfigValue *value);

/**
 * Returns the inner i64. Returns 0 if the variant is not Int or the
 * handle is null.
 */
int64_t ovstorage_config_value_as_int(const OvStorage_ConfigValue *value);

/**
 * Returns the inner bool. Returns false if the variant is not Bool
 * or the handle is null.
 */
bool ovstorage_config_value_as_bool(const OvStorage_ConfigValue *value);

/**
 * Returns a borrowed `*const c_char` pointing at the reserialized TOML
 * payload, valid until the handle is destroyed. Returns null if the
 * variant is not Toml or the handle is null.
 */
const char *ovstorage_config_value_as_toml(const OvStorage_ConfigValue *value);

OvStorage_SecretValue *ovstorage_secret_value_create_bytes(const uint8_t *data, size_t len);

OvStorage_SecretValue *ovstorage_secret_value_create_file(const uint8_t *data, size_t len);

OvStorage_SecretValue *ovstorage_secret_value_create_oauth_token(const uint8_t *token,
                                                                 size_t token_len,
                                                                 const uint8_t *refresh,
                                                                 size_t refresh_len,
                                                                 bool has_refresh,
                                                                 uint64_t expires_at_unix_nanos,
                                                                 bool has_expires_at);

OvStorage_SecretValue *ovstorage_secret_value_create_mtls_cert_pair(const uint8_t *cert_pem,
                                                                    size_t cert_len,
                                                                    const uint8_t *key_pem,
                                                                    size_t key_len);

OvStorage_SecretValue *ovstorage_secret_value_create_system_identity(void);

void ovstorage_secret_value_destroy(OvStorage_SecretValue *value);

OvStorage_ConnectionRequest *ovstorage_connection_request_create(const char *backend_kind);

void ovstorage_connection_request_destroy(OvStorage_ConnectionRequest *request);

/**
 * Set the request's display name. Pass `NULL` to clear.
 */
void ovstorage_connection_request_set_display_name(OvStorage_ConnectionRequest *request,
                                                   const char *display_name);

void ovstorage_connection_request_set_persist(OvStorage_ConnectionRequest *request, bool persist);

/**
 * Add a config entry to the request. On success, the request takes
 * ownership of `value` and the caller's `*value` is invalidated. On
 * failure (null arg, non-UTF-8 key, request already consumed), the
 * caller still owns `value` and must `_destroy` it.
 *
 * Returns `true` on success, `false` on error.
 */
bool ovstorage_connection_request_add_config(OvStorage_ConnectionRequest *request,
                                             const char *key,
                                             OvStorage_ConfigValue *value);

/**
 * Add a credential entry to the request. On success, the request
 * takes ownership of `value` and the caller's `*value` is invalidated.
 * On failure (null arg, non-UTF-8 key, request already consumed), the
 * caller still owns `value` and must `_destroy` it.
 *
 * Returns `true` on success, `false` on error.
 */
bool ovstorage_connection_request_add_credential(OvStorage_ConnectionRequest *request,
                                                 const char *key,
                                                 OvStorage_SecretValue *value);

OvStorage_SecretBundle *ovstorage_secret_bundle_create(void);

void ovstorage_secret_bundle_destroy(OvStorage_SecretBundle *bundle);

/**
 * Add a credential entry to the bundle. On success, the bundle takes
 * ownership of `value` and the caller's `*value` is invalidated. On
 * failure (null arg, non-UTF-8 key, bundle already consumed), the
 * caller still owns `value` and must `_destroy` it.
 *
 * Returns `true` on success, `false` on error.
 */
bool ovstorage_secret_bundle_add(OvStorage_SecretBundle *bundle,
                                 const char *key,
                                 OvStorage_SecretValue *value);

void ovstorage_connection_destroy(OvStorage_Connection *connection);

const char *ovstorage_connection_id(const OvStorage_Connection *connection);

const char *ovstorage_connection_backend_kind(const OvStorage_Connection *connection);

const char *ovstorage_connection_display_name(const OvStorage_Connection *connection);

bool ovstorage_connection_has_last_probed(const OvStorage_Connection *connection);

uint64_t ovstorage_connection_last_probed_unix_nanos(const OvStorage_Connection *connection);

size_t ovstorage_connection_address_count(const OvStorage_Connection *connection);

const char *ovstorage_connection_address_at(const OvStorage_Connection *connection, size_t index);

size_t ovstorage_connection_user_metadata_count(const OvStorage_Connection *connection);

const char *ovstorage_connection_user_metadata_key(const OvStorage_Connection *connection,
                                                   size_t index);

const char *ovstorage_connection_user_metadata_value(const OvStorage_Connection *connection,
                                                     size_t index);

/**
 * Fill the caller-provided `out` with the connection's capabilities.
 * Caller must initialize `out->struct_size = sizeof(...)` before
 * calling. No-op if `connection` or `out` is null.
 */
void ovstorage_connection_capabilities(const OvStorage_Connection *connection,
                                       OvStorage_CapabilitiesV1 *out);

OvStorage_ConnectionSourceKind ovstorage_connection_source_kind(const OvStorage_Connection *connection);

/**
 * Returns the layer for the `Static` variant. Returns
 * `Programmatic` for any other variant (caller should check
 * `_source_kind` first).
 */
OvStorage_ConfigLayer ovstorage_connection_source_static_layer(const OvStorage_Connection *connection);

/**
 * Returns `persisted` for the `Runtime` variant. Returns false for
 * any other variant.
 */
bool ovstorage_connection_source_runtime_persisted(const OvStorage_Connection *connection);

/**
 * Returns the broker principal cstring for the `BrokerDelivered`
 * variant. Returns null for any other variant. Borrowed; valid as
 * long as the connection handle is.
 */
const char *ovstorage_connection_source_broker_principal(const OvStorage_Connection *connection);

OvStorage_ConnectionAuthStateKind ovstorage_connection_auth_state_kind(const OvStorage_Connection *connection);

/**
 * Returns the error message for the AuthFailed variant. Returns
 * NULL for any other variant.
 */
const char *ovstorage_connection_auth_state_failed_message(const OvStorage_Connection *connection);

/**
 * Returns the failed-attempt count for the `AuthFailed` variant.
 * Returns 0 for any other variant.
 */
uint32_t ovstorage_connection_auth_state_failed_attempts(const OvStorage_Connection *connection);

void ovstorage_connection_list_destroy(OvStorage_ConnectionList *list);

size_t ovstorage_connection_list_len(const OvStorage_ConnectionList *list);

/**
 * Returns a borrowed `*const Connection` valid until the list handle
 * is destroyed. Returns null if `index` is out of range.
 */
const OvStorage_Connection *ovstorage_connection_list_item_at(const OvStorage_ConnectionList *list,
                                                              size_t index);

OvStorage_OvResolvedCredentialBundle *ovstorage_resolved_credential_bundle_create(void);

void ovstorage_resolved_credential_bundle_destroy(OvStorage_OvResolvedCredentialBundle *bundle);

/**
 * Add a `(key, value)` field to a credential bundle. Consumes the
 * `SecretValue` handle on success — the caller must NOT call
 * `ovstorage_secret_value_destroy` on it after a successful return.
 * On failure the value is dropped here, so the caller never
 * double-frees.
 */
OvStorage_Status ovstorage_resolved_credential_bundle_add_field(OvStorage_OvResolvedCredentialBundle *bundle,
                                                                const char *key,
                                                                OvStorage_SecretValue *value,
                                                                OvStorage_Error *out_error);

/**
 * Inject a credential into the cache, bypassing the provider chain.
 * Async; fires `on_complete` from the runtime.
 *
 * `backend_id` and `principal_id` are borrowed C-strings; copied at
 * prologue time. `credential->bundle` is consumed on success — do
 * NOT call `ovstorage_resolved_credential_bundle_destroy` on it
 * after a successful return.
 */
void ovstorage_library_set_credential(OvStorage_Library *library,
                                      const char *backend_id,
                                      const char *principal_id,
                                      const OvStorage_OvResolvedCredentialV1 *credential,
                                      OvStorage_StatusCallback on_complete,
                                      void *user_data);

void ovstorage_address_visibility_override_destroy(OvStorage_AddressVisibilityOverride *o);

const char *ovstorage_address_visibility_override_address(const OvStorage_AddressVisibilityOverride *o);

OvStorage_AddressVisibility ovstorage_address_visibility_override_visibility(const OvStorage_AddressVisibilityOverride *o);

bool ovstorage_address_visibility_override_persisted(const OvStorage_AddressVisibilityOverride *o);

void ovstorage_address_visibility_override_list_destroy(OvStorage_AddressVisibilityOverrideList *list);

size_t ovstorage_address_visibility_override_list_len(const OvStorage_AddressVisibilityOverrideList *list);

const OvStorage_AddressVisibilityOverride *ovstorage_address_visibility_override_list_item_at(const OvStorage_AddressVisibilityOverrideList *list,
                                                                                              size_t index);

void ovstorage_address_root_destroy(OvStorage_AddressRoot *root);

const char *ovstorage_address_root_address(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_backend_kind(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_display_name(const OvStorage_AddressRoot *root);

bool ovstorage_address_root_has_connection_id(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_connection_id(const OvStorage_AddressRoot *root);

OvStorage_AddressVisibility ovstorage_address_root_visibility(const OvStorage_AddressRoot *root);

void ovstorage_address_root_capabilities(const OvStorage_AddressRoot *root,
                                         OvStorage_CapabilitiesV1 *out);

OvStorage_RouteSourceKind ovstorage_address_root_source_kind(const OvStorage_AddressRoot *root);

/**
 * Returns the alias `to` URL for the Alias variant. Null otherwise.
 */
const char *ovstorage_address_root_source_alias_to(const OvStorage_AddressRoot *root);

/**
 * Returns the alias-source kind for the Alias variant. Returns
 * `Runtime` for any other parent variant (safe default).
 */
OvStorage_AliasSourceKind ovstorage_address_root_source_alias_source_kind(const OvStorage_AddressRoot *root);

OvStorage_ConfigLayer ovstorage_address_root_source_alias_source_static_layer(const OvStorage_AddressRoot *root);

bool ovstorage_address_root_source_alias_source_runtime_persisted(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_source_alias_source_broker_principal(const OvStorage_AddressRoot *root);

OvStorage_ConfigLayer ovstorage_address_root_source_static_layer(const OvStorage_AddressRoot *root);

/**
 * Returns the connection_id for the ConnectionContributed and
 * BrokerDelivered variants. Returns null otherwise.
 */
const char *ovstorage_address_root_source_connection_id(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_source_broker_principal(const OvStorage_AddressRoot *root);

size_t ovstorage_address_root_user_metadata_count(const OvStorage_AddressRoot *root);

const char *ovstorage_address_root_user_metadata_key(const OvStorage_AddressRoot *root,
                                                     size_t index);

const char *ovstorage_address_root_user_metadata_value(const OvStorage_AddressRoot *root,
                                                       size_t index);

void ovstorage_address_root_list_destroy(OvStorage_AddressRootList *list);

size_t ovstorage_address_root_list_len(const OvStorage_AddressRootList *list);

const OvStorage_AddressRoot *ovstorage_address_root_list_item_at(const OvStorage_AddressRootList *list,
                                                                 size_t index);

void ovstorage_backend_kind_descriptor_destroy(OvStorage_BackendKindDescriptor *d);

const char *ovstorage_backend_kind_descriptor_kind(const OvStorage_BackendKindDescriptor *d);

const char *ovstorage_backend_kind_descriptor_display_name(const OvStorage_BackendKindDescriptor *d);

/**
 * Returns null if the descriptor has no `description` set.
 */
const char *ovstorage_backend_kind_descriptor_description(const OvStorage_BackendKindDescriptor *d);

bool ovstorage_backend_kind_descriptor_supports_runtime_add(const OvStorage_BackendKindDescriptor *d);

/**
 * Returns the icon byte length, or 0 if no icon is set.
 */
size_t ovstorage_backend_kind_descriptor_icon_len(const OvStorage_BackendKindDescriptor *d);

/**
 * Returns a borrowed pointer to the icon bytes, valid while the
 * descriptor handle lives. Returns null if no icon is set.
 */
const uint8_t *ovstorage_backend_kind_descriptor_icon_data(const OvStorage_BackendKindDescriptor *d);

void ovstorage_backend_kind_descriptor_list_destroy(OvStorage_BackendKindDescriptorList *list);

size_t ovstorage_backend_kind_descriptor_list_len(const OvStorage_BackendKindDescriptorList *list);

const OvStorage_BackendKindDescriptor *ovstorage_backend_kind_descriptor_list_item_at(const OvStorage_BackendKindDescriptorList *list,
                                                                                      size_t index);

void ovstorage_stat(OvStorage_Library *library,
                    const char *address,
                    const OvStorage_StatOptionsV1 *options,
                    const OvStorage_CancelToken *cancel,
                    OvStorage_InfoCallback on_complete,
                    void *user_data);

void ovstorage_read_bytes(OvStorage_Library *library,
                          const char *address,
                          const OvStorage_ReadOptionsV1 *options,
                          const OvStorage_CancelToken *cancel,
                          OvStorage_ReadBytesCallback on_complete,
                          void *user_data);

void ovstorage_read_stream(OvStorage_Library *library,
                           const char *address,
                           const OvStorage_ReadOptionsV1 *options,
                           const OvStorage_CancelToken *cancel,
                           OvStorage_ReadStreamCallback on_complete,
                           void *user_data);

void ovstorage_read_local_file(OvStorage_Library *library,
                               const char *address,
                               const OvStorage_ReadOptionsV1 *options,
                               const OvStorage_CancelToken *cancel,
                               OvStorage_ReadLocalFileCallback on_complete,
                               void *user_data);

void ovstorage_write(OvStorage_Library *library,
                     const char *address,
                     const uint8_t *data,
                     size_t len,
                     const OvStorage_WriteOptionsV1 *options,
                     const OvStorage_CancelToken *cancel,
                     OvStorage_InfoCallback on_complete,
                     void *user_data);

void ovstorage_delete(OvStorage_Library *library,
                      const char *address,
                      const OvStorage_CancelToken *cancel,
                      OvStorage_StatusCallback on_complete,
                      void *user_data);

void ovstorage_list(OvStorage_Library *library,
                    const char *prefix,
                    const OvStorage_ListOptionsV1 *options,
                    const OvStorage_CancelToken *cancel,
                    OvStorage_ListCallback on_complete,
                    void *user_data);

void ovstorage_list_versions(OvStorage_Library *library,
                             const char *address,
                             const OvStorage_ListVersionsOptionsV1 *options,
                             const OvStorage_CancelToken *cancel,
                             OvStorage_ListVersionsCallback on_complete,
                             void *user_data);

void ovstorage_copy(OvStorage_Library *library,
                    const char *src,
                    const char *dest,
                    const OvStorage_CancelToken *cancel,
                    OvStorage_InfoCallback on_complete,
                    void *user_data);

void ovstorage_rename(OvStorage_Library *library,
                      const char *src,
                      const char *dest,
                      const OvStorage_CancelToken *cancel,
                      OvStorage_StatusCallback on_complete,
                      void *user_data);

void ovstorage_create_directory(OvStorage_Library *library,
                                const char *address,
                                const OvStorage_CreateDirectoryOptionsV1 *options,
                                const OvStorage_CancelToken *cancel,
                                OvStorage_InfoCallback on_complete,
                                void *user_data);

void ovstorage_delete_directory(OvStorage_Library *library,
                                const char *address,
                                const OvStorage_DeleteDirectoryOptionsV1 *options,
                                const OvStorage_CancelToken *cancel,
                                OvStorage_StatusCallback on_complete,
                                void *user_data);

void ovstorage_update_metadata(OvStorage_Library *library,
                               const char *address,
                               const OvStorage_UpdateMetadataOptions *options,
                               const OvStorage_CancelToken *cancel,
                               OvStorage_InfoCallback on_complete,
                               void *user_data);

void ovstorage_check_access(OvStorage_Library *library,
                            const char *address,
                            OvStorage_AccessOps ops,
                            const OvStorage_CancelToken *cancel,
                            OvStorage_CheckAccessCallback on_complete,
                            void *user_data);

/**
 * Register a new connection on the library. The result is delivered
 * through `on_complete` as a `*mut Connection` the caller owns and
 * must free with `ovstorage_connection_destroy`.
 *
 * Ownership rules for `request`:
 * - On a prologue validation error (null library, null/already-
 *   consumed request), `*request` is NOT consumed — the caller
 *   still owns it and must free with
 *   `ovstorage_connection_request_destroy` (or fix and retry).
 * - On any other path (callback fires with success or with a
 *   library-side error), the request was passed to the library and
 *   is consumed; the caller must NOT call `_destroy` on it.
 */
void ovstorage_library_add_connection(OvStorage_Library *library,
                                      OvStorage_ConnectionRequest *request,
                                      const OvStorage_CancelToken *cancel,
                                      OvStorage_ConnectionCallback on_complete,
                                      void *user_data);

/**
 * List all connections registered on the library.
 */
void ovstorage_library_list_connections(OvStorage_Library *library,
                                        const OvStorage_CancelToken *cancel,
                                        OvStorage_ConnectionListCallback on_complete,
                                        void *user_data);

/**
 * Load and register a single plugin cdylib at `path` (UTF-8 nul-terminated).
 * Idempotent — re-registering an already-known backend kind replaces the
 * prior factory entry.
 *
 * # Safety
 *
 * `dlopen` runs platform loader hooks; `path` must point to a trusted
 * plugin file.
 */
void ovstorage_library_load_plugin(OvStorage_Library *library,
                                   const char *path,
                                   OvStorage_StatusCallback on_complete,
                                   void *user_data);

/**
 * Scan a directory for `libovstorage_plugin_*.{so,dylib,dll}` and load each.
 * `dir = NULL` resolves to `OVSTORAGE_PLUGIN_DIR` or `<exe-dir>/plugins/`.
 * A non-existent directory fires success with no plugins loaded.
 *
 * # Safety
 *
 * Each candidate is `dlopen`'d in-process; trust the directory contents.
 */
void ovstorage_library_load_plugins_from_dir(OvStorage_Library *library,
                                             const char *dir,
                                             OvStorage_StatusCallback on_complete,
                                             void *user_data);

/**
 * Load `ovstorage.toml` and register every `[[connections]]` entry on the
 * live library. `path = NULL` uses the default search path
 * (`./ovstorage.toml` then `$XDG_CONFIG_HOME/ovstorage/ovstorage.toml`).
 * On success `on_complete` fires with the freshly registered list. No file
 * at `NULL` search path returns an empty list.
 *
 * Credential refs resolve against the same `SecretStore` namespace the
 * library was initialized with, so a CLI `write-config --secrets keyring`
 * flow is picked up transparently.
 */
void ovstorage_library_load_config(OvStorage_Library *library,
                                   const char *path,
                                   OvStorage_ConnectionListCallback on_complete,
                                   void *user_data);

/**
 * Remove a registered connection by id.
 */
void ovstorage_library_remove_connection(OvStorage_Library *library,
                                         const char *connection_id,
                                         const OvStorage_CancelToken *cancel,
                                         OvStorage_StatusCallback on_complete,
                                         void *user_data);

/**
 * Refresh the credentials on an existing connection. Consumes the
 * `credentials` handle on success; on prologue error the caller
 * still owns it and must free with `ovstorage_secret_bundle_destroy`.
 */
void ovstorage_library_update_connection_credentials(OvStorage_Library *library,
                                                     const char *connection_id,
                                                     OvStorage_SecretBundle *credentials,
                                                     const OvStorage_CancelToken *cancel,
                                                     OvStorage_ConnectionCallback on_complete,
                                                     void *user_data);

/**
 * Drive the connection's authentication flow. The library returns
 * a stream of `AuthEvent`s; this thunk drains it and fires the
 * multi-fire callback once per event, with a final `done=true`
 * fire on end-of-stream or terminal error. Cancellation is polled
 * between events.
 */
void ovstorage_library_authenticate_connection(OvStorage_Library *library,
                                               const char *connection_id,
                                               const OvStorage_CancelToken *cancel,
                                               OvStorage_AuthEventCallback on_complete,
                                               void *user_data);

/**
 * Add an alias to the library. Consumes the request handle on
 * success; on prologue error the caller still owns it and must
 * free with `ovstorage_alias_request_destroy`.
 */
void ovstorage_library_add_alias(OvStorage_Library *library,
                                 OvStorage_AliasRequest *request,
                                 const OvStorage_CancelToken *cancel,
                                 OvStorage_AliasCallback on_complete,
                                 void *user_data);

/**
 * Remove an alias by id.
 */
void ovstorage_library_remove_alias(OvStorage_Library *library,
                                    const char *alias_id,
                                    const OvStorage_CancelToken *cancel,
                                    OvStorage_StatusCallback on_complete,
                                    void *user_data);

/**
 * List all aliases registered on the library.
 */
void ovstorage_library_list_aliases(OvStorage_Library *library,
                                    const OvStorage_CancelToken *cancel,
                                    OvStorage_AliasListCallback on_complete,
                                    void *user_data);

/**
 * Watch address-root table changes. Emits a full snapshot on subscribe
 * and after every routing-table change until cancelled or shutdown.
 */
void ovstorage_library_watch_address_roots(OvStorage_Library *library,
                                           const OvStorage_CancelToken *cancel,
                                           OvStorage_AddressRootWatchCallback on_complete,
                                           void *user_data);

/**
 * Set or update an address-visibility override. Returns the
 * resulting `AddressVisibilityOverride` via the callback (caller
 * owns; free with `ovstorage_address_visibility_override_destroy`).
 */
void ovstorage_library_set_address_visibility(OvStorage_Library *library,
                                              const char *address,
                                              OvStorage_AddressVisibility visibility,
                                              bool persist,
                                              const OvStorage_CancelToken *cancel,
                                              OvStorage_AddressVisibilityOverrideCallback on_complete,
                                              void *user_data);

void ovstorage_library_list_address_visibility_overrides(OvStorage_Library *library,
                                                         const OvStorage_CancelToken *cancel,
                                                         OvStorage_AddressVisibilityOverrideListCallback on_complete,
                                                         void *user_data);

void ovstorage_library_list_address_roots(OvStorage_Library *library,
                                          const OvStorage_CancelToken *cancel,
                                          OvStorage_AddressRootListCallback on_complete,
                                          void *user_data);

void ovstorage_library_list_backend_kinds(OvStorage_Library *library,
                                          const OvStorage_CancelToken *cancel,
                                          OvStorage_BackendKindDescriptorListCallback on_complete,
                                          void *user_data);

void ovstorage_library_capabilities_for(OvStorage_Library *library,
                                        const char *prefix,
                                        const OvStorage_CancelToken *cancel,
                                        OvStorage_CapabilitiesCallback on_complete,
                                        void *user_data);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OVSTORAGE_H */
