# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[pytest]
testpaths = conformance_tests
python_files = test_*.py *_test.py *.feature
python_classes = Test*
python_functions = test_*
markers =
    conformance_tests: marks tests as conformance tests
    optional: mark test to allow for selection of running non-optional tests or only optional tests
