# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ovstorage-plugin-opendal"
version = "0.1.0"
edition = "2024"
description = "OpenDAL-compatible ovstorage backend crate."
license = "Apache-2.0"

[dependencies]
ovstorage-plugin.workspace = true
async-trait.workspace = true
futures.workspace = true
opendal.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
