# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "ovstorage-broker-protocol"
version = "0.1.0"
edition = "2024"
description = "Generated protobuf/tonic protocol for ovstorage brokered mode."
license = "Apache-2.0"

[dependencies]
async-trait.workspace = true
futures.workspace = true
ovstorage-plugin.workspace = true
prost.workspace = true
tonic.workspace = true

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
