# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Stubtest drift detection.

`ovstorage.pyi` is hand-maintained alongside the PyO3 runtime in
`src/lib.rs`. This test runs `mypy.stubtest` against the installed
module and fails on drift the code review flagged — missing methods,
stub-only parameters, missing fields, signature mismatches.

PyO3-impedance noise (`@final` / `@disjoint_base` markers, the
submodule .so) is filtered out because PyO3 classes are intrinsically
final at runtime regardless of stub annotation; flagging every class
would dominate the output.

Skipped when mypy is not available so the existing test suite stays
runnable without an extra dev-dep install.
"""
from __future__ import annotations

import io
import sys

import pytest


PYO3_NOISE_PHRASES = (
    "cannot be subclassed at runtime",
    "is a disjoint base at runtime",
    "ovstorage.ovstorage failed to find stubs",
    # `__all__` is auto-generated by PyO3; declaring an exact list in
    # the stub is a maintenance burden out of proportion to the value.
    # Real drift in surface methods/fields is what this test catches.
    "ovstorage.__all__",
)


def _is_drift_error(line: str) -> bool:
    if not line.startswith("error: "):
        return False
    return not any(phrase in line for phrase in PYO3_NOISE_PHRASES)


def test_stub_matches_runtime() -> None:
    try:
        from mypy import stubtest
    except ImportError:
        pytest.skip("mypy not installed; run `pip install mypy` to enable stubtest")

    out = io.StringIO()
    saved = sys.stdout
    sys.stdout = out
    try:
        options = stubtest.parse_options(["ovstorage"])
        stubtest.test_stubs(options)
    finally:
        sys.stdout = saved

    drift_lines = [line for line in out.getvalue().splitlines() if _is_drift_error(line)]
    assert not drift_lines, "stubtest reported drift:\n" + "\n".join(drift_lines)
